package com.judge.demo.Entity;

import java.io.Serializable;
import java.util.Date;

public class AliDianpu implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ali_dianpu.dianpu_record_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private Long dianpuRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ali_dianpu.id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ali_dianpu.buy_ni
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String buyNi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ali_dianpu.sell_ni
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String sellNi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ali_dianpu.money
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ali_dianpu.title
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ali_dianpu.num
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ali_dianpu.buy_name
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String buyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ali_dianpu.buy_phone
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String buyPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ali_dianpu.buy_shen
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String buyShen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ali_dianpu.buy_city
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String buyCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ali_dianpu.buy_region
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String buyRegion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ali_dianpu.buy_addres
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String buyAddres;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ali_dianpu.c_date
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private Date cDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ali_dianpu.index
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String index;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ali_dianpu
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ali_dianpu.dianpu_record_id
     *
     * @return the value of ali_dianpu.dianpu_record_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public Long getDianpuRecordId() {
        return dianpuRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ali_dianpu.dianpu_record_id
     *
     * @param dianpuRecordId the value for ali_dianpu.dianpu_record_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setDianpuRecordId(Long dianpuRecordId) {
        this.dianpuRecordId = dianpuRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ali_dianpu.id
     *
     * @return the value of ali_dianpu.id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ali_dianpu.id
     *
     * @param id the value for ali_dianpu.id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ali_dianpu.buy_ni
     *
     * @return the value of ali_dianpu.buy_ni
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getBuyNi() {
        return buyNi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ali_dianpu.buy_ni
     *
     * @param buyNi the value for ali_dianpu.buy_ni
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setBuyNi(String buyNi) {
        this.buyNi = buyNi == null ? null : buyNi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ali_dianpu.sell_ni
     *
     * @return the value of ali_dianpu.sell_ni
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getSellNi() {
        return sellNi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ali_dianpu.sell_ni
     *
     * @param sellNi the value for ali_dianpu.sell_ni
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setSellNi(String sellNi) {
        this.sellNi = sellNi == null ? null : sellNi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ali_dianpu.money
     *
     * @return the value of ali_dianpu.money
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ali_dianpu.money
     *
     * @param money the value for ali_dianpu.money
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ali_dianpu.title
     *
     * @return the value of ali_dianpu.title
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ali_dianpu.title
     *
     * @param title the value for ali_dianpu.title
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ali_dianpu.num
     *
     * @return the value of ali_dianpu.num
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ali_dianpu.num
     *
     * @param num the value for ali_dianpu.num
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ali_dianpu.buy_name
     *
     * @return the value of ali_dianpu.buy_name
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getBuyName() {
        return buyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ali_dianpu.buy_name
     *
     * @param buyName the value for ali_dianpu.buy_name
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setBuyName(String buyName) {
        this.buyName = buyName == null ? null : buyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ali_dianpu.buy_phone
     *
     * @return the value of ali_dianpu.buy_phone
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getBuyPhone() {
        return buyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ali_dianpu.buy_phone
     *
     * @param buyPhone the value for ali_dianpu.buy_phone
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setBuyPhone(String buyPhone) {
        this.buyPhone = buyPhone == null ? null : buyPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ali_dianpu.buy_shen
     *
     * @return the value of ali_dianpu.buy_shen
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getBuyShen() {
        return buyShen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ali_dianpu.buy_shen
     *
     * @param buyShen the value for ali_dianpu.buy_shen
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setBuyShen(String buyShen) {
        this.buyShen = buyShen == null ? null : buyShen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ali_dianpu.buy_city
     *
     * @return the value of ali_dianpu.buy_city
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getBuyCity() {
        return buyCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ali_dianpu.buy_city
     *
     * @param buyCity the value for ali_dianpu.buy_city
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setBuyCity(String buyCity) {
        this.buyCity = buyCity == null ? null : buyCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ali_dianpu.buy_region
     *
     * @return the value of ali_dianpu.buy_region
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getBuyRegion() {
        return buyRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ali_dianpu.buy_region
     *
     * @param buyRegion the value for ali_dianpu.buy_region
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setBuyRegion(String buyRegion) {
        this.buyRegion = buyRegion == null ? null : buyRegion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ali_dianpu.buy_addres
     *
     * @return the value of ali_dianpu.buy_addres
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getBuyAddres() {
        return buyAddres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ali_dianpu.buy_addres
     *
     * @param buyAddres the value for ali_dianpu.buy_addres
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setBuyAddres(String buyAddres) {
        this.buyAddres = buyAddres == null ? null : buyAddres.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ali_dianpu.c_date
     *
     * @return the value of ali_dianpu.c_date
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public Date getcDate() {
        return cDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ali_dianpu.c_date
     *
     * @param cDate the value for ali_dianpu.c_date
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setcDate(Date cDate) {
        this.cDate = cDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ali_dianpu.index
     *
     * @return the value of ali_dianpu.index
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ali_dianpu.index
     *
     * @param index the value for ali_dianpu.index
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setIndex(String index) {
        this.index = index == null ? null : index.trim();
    }
}