package com.judge.demo.Entity;

import java.io.Serializable;
import java.util.Date;

public class BuyRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_record.buy_record_id
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private Long buyRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_record.buy_record_order_id
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private String buyRecordOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_record.buy_record_order_fee
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private Double buyRecordOrderFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_record.buy_record_buyer_account
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private String buyRecordBuyerAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_record.buy_record_seller_account
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private String buyRecordSellerAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_record.buy_record_goods_title
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private String buyRecordGoodsTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_record.buy_record_goods_price
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private Double buyRecordGoodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_record.buy_record_goods_num
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private Integer buyRecordGoodsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_record.buy_record_address
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private String buyRecordAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_record.buy_record_status
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private Integer buyRecordStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_record.buy_record_time
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private Date buyRecordTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_record.buy_record_receiver_name
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private String buyRecordReceiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_record.buy_record_receiver_phone
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private String buyRecordReceiverPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_record.buy_record_index
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private String buyRecordIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buy_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_record.buy_record_id
     *
     * @return the value of buy_record.buy_record_id
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public Long getBuyRecordId() {
        return buyRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_record.buy_record_id
     *
     * @param buyRecordId the value for buy_record.buy_record_id
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setBuyRecordId(Long buyRecordId) {
        this.buyRecordId = buyRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_record.buy_record_order_id
     *
     * @return the value of buy_record.buy_record_order_id
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public String getBuyRecordOrderId() {
        return buyRecordOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_record.buy_record_order_id
     *
     * @param buyRecordOrderId the value for buy_record.buy_record_order_id
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setBuyRecordOrderId(String buyRecordOrderId) {
        this.buyRecordOrderId = buyRecordOrderId == null ? null : buyRecordOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_record.buy_record_order_fee
     *
     * @return the value of buy_record.buy_record_order_fee
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public Double getBuyRecordOrderFee() {
        return buyRecordOrderFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_record.buy_record_order_fee
     *
     * @param buyRecordOrderFee the value for buy_record.buy_record_order_fee
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setBuyRecordOrderFee(Double buyRecordOrderFee) {
        this.buyRecordOrderFee = buyRecordOrderFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_record.buy_record_buyer_account
     *
     * @return the value of buy_record.buy_record_buyer_account
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public String getBuyRecordBuyerAccount() {
        return buyRecordBuyerAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_record.buy_record_buyer_account
     *
     * @param buyRecordBuyerAccount the value for buy_record.buy_record_buyer_account
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setBuyRecordBuyerAccount(String buyRecordBuyerAccount) {
        this.buyRecordBuyerAccount = buyRecordBuyerAccount == null ? null : buyRecordBuyerAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_record.buy_record_seller_account
     *
     * @return the value of buy_record.buy_record_seller_account
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public String getBuyRecordSellerAccount() {
        return buyRecordSellerAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_record.buy_record_seller_account
     *
     * @param buyRecordSellerAccount the value for buy_record.buy_record_seller_account
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setBuyRecordSellerAccount(String buyRecordSellerAccount) {
        this.buyRecordSellerAccount = buyRecordSellerAccount == null ? null : buyRecordSellerAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_record.buy_record_goods_title
     *
     * @return the value of buy_record.buy_record_goods_title
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public String getBuyRecordGoodsTitle() {
        return buyRecordGoodsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_record.buy_record_goods_title
     *
     * @param buyRecordGoodsTitle the value for buy_record.buy_record_goods_title
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setBuyRecordGoodsTitle(String buyRecordGoodsTitle) {
        this.buyRecordGoodsTitle = buyRecordGoodsTitle == null ? null : buyRecordGoodsTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_record.buy_record_goods_price
     *
     * @return the value of buy_record.buy_record_goods_price
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public Double getBuyRecordGoodsPrice() {
        return buyRecordGoodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_record.buy_record_goods_price
     *
     * @param buyRecordGoodsPrice the value for buy_record.buy_record_goods_price
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setBuyRecordGoodsPrice(Double buyRecordGoodsPrice) {
        this.buyRecordGoodsPrice = buyRecordGoodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_record.buy_record_goods_num
     *
     * @return the value of buy_record.buy_record_goods_num
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public Integer getBuyRecordGoodsNum() {
        return buyRecordGoodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_record.buy_record_goods_num
     *
     * @param buyRecordGoodsNum the value for buy_record.buy_record_goods_num
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setBuyRecordGoodsNum(Integer buyRecordGoodsNum) {
        this.buyRecordGoodsNum = buyRecordGoodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_record.buy_record_address
     *
     * @return the value of buy_record.buy_record_address
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public String getBuyRecordAddress() {
        return buyRecordAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_record.buy_record_address
     *
     * @param buyRecordAddress the value for buy_record.buy_record_address
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setBuyRecordAddress(String buyRecordAddress) {
        this.buyRecordAddress = buyRecordAddress == null ? null : buyRecordAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_record.buy_record_status
     *
     * @return the value of buy_record.buy_record_status
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public Integer getBuyRecordStatus() {
        return buyRecordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_record.buy_record_status
     *
     * @param buyRecordStatus the value for buy_record.buy_record_status
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setBuyRecordStatus(Integer buyRecordStatus) {
        this.buyRecordStatus = buyRecordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_record.buy_record_time
     *
     * @return the value of buy_record.buy_record_time
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public Date getBuyRecordTime() {
        return buyRecordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_record.buy_record_time
     *
     * @param buyRecordTime the value for buy_record.buy_record_time
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setBuyRecordTime(Date buyRecordTime) {
        this.buyRecordTime = buyRecordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_record.buy_record_receiver_name
     *
     * @return the value of buy_record.buy_record_receiver_name
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public String getBuyRecordReceiverName() {
        return buyRecordReceiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_record.buy_record_receiver_name
     *
     * @param buyRecordReceiverName the value for buy_record.buy_record_receiver_name
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setBuyRecordReceiverName(String buyRecordReceiverName) {
        this.buyRecordReceiverName = buyRecordReceiverName == null ? null : buyRecordReceiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_record.buy_record_receiver_phone
     *
     * @return the value of buy_record.buy_record_receiver_phone
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public String getBuyRecordReceiverPhone() {
        return buyRecordReceiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_record.buy_record_receiver_phone
     *
     * @param buyRecordReceiverPhone the value for buy_record.buy_record_receiver_phone
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setBuyRecordReceiverPhone(String buyRecordReceiverPhone) {
        this.buyRecordReceiverPhone = buyRecordReceiverPhone == null ? null : buyRecordReceiverPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_record.buy_record_index
     *
     * @return the value of buy_record.buy_record_index
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public String getBuyRecordIndex() {
        return buyRecordIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_record.buy_record_index
     *
     * @param buyRecordIndex the value for buy_record.buy_record_index
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setBuyRecordIndex(String buyRecordIndex) {
        this.buyRecordIndex = buyRecordIndex == null ? null : buyRecordIndex.trim();
    }
}