package com.judge.demo.Entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BuyRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buy_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buy_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buy_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buy_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buy_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public BuyRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table buy_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBuyRecordIdIsNull() {
            addCriterion("buy_record_id is null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordIdIsNotNull() {
            addCriterion("buy_record_id is not null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordIdEqualTo(Long value) {
            addCriterion("buy_record_id =", value, "buyRecordId");
            return (Criteria) this;
        }

        public Criteria andBuyRecordIdNotEqualTo(Long value) {
            addCriterion("buy_record_id <>", value, "buyRecordId");
            return (Criteria) this;
        }

        public Criteria andBuyRecordIdGreaterThan(Long value) {
            addCriterion("buy_record_id >", value, "buyRecordId");
            return (Criteria) this;
        }

        public Criteria andBuyRecordIdGreaterThanOrEqualTo(Long value) {
            addCriterion("buy_record_id >=", value, "buyRecordId");
            return (Criteria) this;
        }

        public Criteria andBuyRecordIdLessThan(Long value) {
            addCriterion("buy_record_id <", value, "buyRecordId");
            return (Criteria) this;
        }

        public Criteria andBuyRecordIdLessThanOrEqualTo(Long value) {
            addCriterion("buy_record_id <=", value, "buyRecordId");
            return (Criteria) this;
        }

        public Criteria andBuyRecordIdIn(List<Long> values) {
            addCriterion("buy_record_id in", values, "buyRecordId");
            return (Criteria) this;
        }

        public Criteria andBuyRecordIdNotIn(List<Long> values) {
            addCriterion("buy_record_id not in", values, "buyRecordId");
            return (Criteria) this;
        }

        public Criteria andBuyRecordIdBetween(Long value1, Long value2) {
            addCriterion("buy_record_id between", value1, value2, "buyRecordId");
            return (Criteria) this;
        }

        public Criteria andBuyRecordIdNotBetween(Long value1, Long value2) {
            addCriterion("buy_record_id not between", value1, value2, "buyRecordId");
            return (Criteria) this;
        }

        public Criteria andBuyRecordOrderIdIsNull() {
            addCriterion("buy_record_order_id is null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordOrderIdIsNotNull() {
            addCriterion("buy_record_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordOrderIdEqualTo(String value) {
            addCriterion("buy_record_order_id =", value, "buyRecordOrderId");
            return (Criteria) this;
        }

        public Criteria andBuyRecordOrderIdNotEqualTo(String value) {
            addCriterion("buy_record_order_id <>", value, "buyRecordOrderId");
            return (Criteria) this;
        }

        public Criteria andBuyRecordOrderIdGreaterThan(String value) {
            addCriterion("buy_record_order_id >", value, "buyRecordOrderId");
            return (Criteria) this;
        }

        public Criteria andBuyRecordOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("buy_record_order_id >=", value, "buyRecordOrderId");
            return (Criteria) this;
        }

        public Criteria andBuyRecordOrderIdLessThan(String value) {
            addCriterion("buy_record_order_id <", value, "buyRecordOrderId");
            return (Criteria) this;
        }

        public Criteria andBuyRecordOrderIdLessThanOrEqualTo(String value) {
            addCriterion("buy_record_order_id <=", value, "buyRecordOrderId");
            return (Criteria) this;
        }

        public Criteria andBuyRecordOrderIdLike(String value) {
            addCriterion("buy_record_order_id like", value, "buyRecordOrderId");
            return (Criteria) this;
        }

        public Criteria andBuyRecordOrderIdNotLike(String value) {
            addCriterion("buy_record_order_id not like", value, "buyRecordOrderId");
            return (Criteria) this;
        }

        public Criteria andBuyRecordOrderIdIn(List<String> values) {
            addCriterion("buy_record_order_id in", values, "buyRecordOrderId");
            return (Criteria) this;
        }

        public Criteria andBuyRecordOrderIdNotIn(List<String> values) {
            addCriterion("buy_record_order_id not in", values, "buyRecordOrderId");
            return (Criteria) this;
        }

        public Criteria andBuyRecordOrderIdBetween(String value1, String value2) {
            addCriterion("buy_record_order_id between", value1, value2, "buyRecordOrderId");
            return (Criteria) this;
        }

        public Criteria andBuyRecordOrderIdNotBetween(String value1, String value2) {
            addCriterion("buy_record_order_id not between", value1, value2, "buyRecordOrderId");
            return (Criteria) this;
        }

        public Criteria andBuyRecordOrderFeeIsNull() {
            addCriterion("buy_record_order_fee is null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordOrderFeeIsNotNull() {
            addCriterion("buy_record_order_fee is not null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordOrderFeeEqualTo(Double value) {
            addCriterion("buy_record_order_fee =", value, "buyRecordOrderFee");
            return (Criteria) this;
        }

        public Criteria andBuyRecordOrderFeeNotEqualTo(Double value) {
            addCriterion("buy_record_order_fee <>", value, "buyRecordOrderFee");
            return (Criteria) this;
        }

        public Criteria andBuyRecordOrderFeeGreaterThan(Double value) {
            addCriterion("buy_record_order_fee >", value, "buyRecordOrderFee");
            return (Criteria) this;
        }

        public Criteria andBuyRecordOrderFeeGreaterThanOrEqualTo(Double value) {
            addCriterion("buy_record_order_fee >=", value, "buyRecordOrderFee");
            return (Criteria) this;
        }

        public Criteria andBuyRecordOrderFeeLessThan(Double value) {
            addCriterion("buy_record_order_fee <", value, "buyRecordOrderFee");
            return (Criteria) this;
        }

        public Criteria andBuyRecordOrderFeeLessThanOrEqualTo(Double value) {
            addCriterion("buy_record_order_fee <=", value, "buyRecordOrderFee");
            return (Criteria) this;
        }

        public Criteria andBuyRecordOrderFeeIn(List<Double> values) {
            addCriterion("buy_record_order_fee in", values, "buyRecordOrderFee");
            return (Criteria) this;
        }

        public Criteria andBuyRecordOrderFeeNotIn(List<Double> values) {
            addCriterion("buy_record_order_fee not in", values, "buyRecordOrderFee");
            return (Criteria) this;
        }

        public Criteria andBuyRecordOrderFeeBetween(Double value1, Double value2) {
            addCriterion("buy_record_order_fee between", value1, value2, "buyRecordOrderFee");
            return (Criteria) this;
        }

        public Criteria andBuyRecordOrderFeeNotBetween(Double value1, Double value2) {
            addCriterion("buy_record_order_fee not between", value1, value2, "buyRecordOrderFee");
            return (Criteria) this;
        }

        public Criteria andBuyRecordBuyerAccountIsNull() {
            addCriterion("buy_record_buyer_account is null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordBuyerAccountIsNotNull() {
            addCriterion("buy_record_buyer_account is not null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordBuyerAccountEqualTo(String value) {
            addCriterion("buy_record_buyer_account =", value, "buyRecordBuyerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyRecordBuyerAccountNotEqualTo(String value) {
            addCriterion("buy_record_buyer_account <>", value, "buyRecordBuyerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyRecordBuyerAccountGreaterThan(String value) {
            addCriterion("buy_record_buyer_account >", value, "buyRecordBuyerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyRecordBuyerAccountGreaterThanOrEqualTo(String value) {
            addCriterion("buy_record_buyer_account >=", value, "buyRecordBuyerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyRecordBuyerAccountLessThan(String value) {
            addCriterion("buy_record_buyer_account <", value, "buyRecordBuyerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyRecordBuyerAccountLessThanOrEqualTo(String value) {
            addCriterion("buy_record_buyer_account <=", value, "buyRecordBuyerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyRecordBuyerAccountLike(String value) {
            addCriterion("buy_record_buyer_account like", value, "buyRecordBuyerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyRecordBuyerAccountNotLike(String value) {
            addCriterion("buy_record_buyer_account not like", value, "buyRecordBuyerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyRecordBuyerAccountIn(List<String> values) {
            addCriterion("buy_record_buyer_account in", values, "buyRecordBuyerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyRecordBuyerAccountNotIn(List<String> values) {
            addCriterion("buy_record_buyer_account not in", values, "buyRecordBuyerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyRecordBuyerAccountBetween(String value1, String value2) {
            addCriterion("buy_record_buyer_account between", value1, value2, "buyRecordBuyerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyRecordBuyerAccountNotBetween(String value1, String value2) {
            addCriterion("buy_record_buyer_account not between", value1, value2, "buyRecordBuyerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyRecordSellerAccountIsNull() {
            addCriterion("buy_record_seller_account is null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordSellerAccountIsNotNull() {
            addCriterion("buy_record_seller_account is not null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordSellerAccountEqualTo(String value) {
            addCriterion("buy_record_seller_account =", value, "buyRecordSellerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyRecordSellerAccountNotEqualTo(String value) {
            addCriterion("buy_record_seller_account <>", value, "buyRecordSellerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyRecordSellerAccountGreaterThan(String value) {
            addCriterion("buy_record_seller_account >", value, "buyRecordSellerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyRecordSellerAccountGreaterThanOrEqualTo(String value) {
            addCriterion("buy_record_seller_account >=", value, "buyRecordSellerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyRecordSellerAccountLessThan(String value) {
            addCriterion("buy_record_seller_account <", value, "buyRecordSellerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyRecordSellerAccountLessThanOrEqualTo(String value) {
            addCriterion("buy_record_seller_account <=", value, "buyRecordSellerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyRecordSellerAccountLike(String value) {
            addCriterion("buy_record_seller_account like", value, "buyRecordSellerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyRecordSellerAccountNotLike(String value) {
            addCriterion("buy_record_seller_account not like", value, "buyRecordSellerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyRecordSellerAccountIn(List<String> values) {
            addCriterion("buy_record_seller_account in", values, "buyRecordSellerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyRecordSellerAccountNotIn(List<String> values) {
            addCriterion("buy_record_seller_account not in", values, "buyRecordSellerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyRecordSellerAccountBetween(String value1, String value2) {
            addCriterion("buy_record_seller_account between", value1, value2, "buyRecordSellerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyRecordSellerAccountNotBetween(String value1, String value2) {
            addCriterion("buy_record_seller_account not between", value1, value2, "buyRecordSellerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsTitleIsNull() {
            addCriterion("buy_record_goods_title is null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsTitleIsNotNull() {
            addCriterion("buy_record_goods_title is not null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsTitleEqualTo(String value) {
            addCriterion("buy_record_goods_title =", value, "buyRecordGoodsTitle");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsTitleNotEqualTo(String value) {
            addCriterion("buy_record_goods_title <>", value, "buyRecordGoodsTitle");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsTitleGreaterThan(String value) {
            addCriterion("buy_record_goods_title >", value, "buyRecordGoodsTitle");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsTitleGreaterThanOrEqualTo(String value) {
            addCriterion("buy_record_goods_title >=", value, "buyRecordGoodsTitle");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsTitleLessThan(String value) {
            addCriterion("buy_record_goods_title <", value, "buyRecordGoodsTitle");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsTitleLessThanOrEqualTo(String value) {
            addCriterion("buy_record_goods_title <=", value, "buyRecordGoodsTitle");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsTitleLike(String value) {
            addCriterion("buy_record_goods_title like", value, "buyRecordGoodsTitle");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsTitleNotLike(String value) {
            addCriterion("buy_record_goods_title not like", value, "buyRecordGoodsTitle");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsTitleIn(List<String> values) {
            addCriterion("buy_record_goods_title in", values, "buyRecordGoodsTitle");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsTitleNotIn(List<String> values) {
            addCriterion("buy_record_goods_title not in", values, "buyRecordGoodsTitle");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsTitleBetween(String value1, String value2) {
            addCriterion("buy_record_goods_title between", value1, value2, "buyRecordGoodsTitle");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsTitleNotBetween(String value1, String value2) {
            addCriterion("buy_record_goods_title not between", value1, value2, "buyRecordGoodsTitle");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsPriceIsNull() {
            addCriterion("buy_record_goods_price is null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsPriceIsNotNull() {
            addCriterion("buy_record_goods_price is not null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsPriceEqualTo(Double value) {
            addCriterion("buy_record_goods_price =", value, "buyRecordGoodsPrice");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsPriceNotEqualTo(Double value) {
            addCriterion("buy_record_goods_price <>", value, "buyRecordGoodsPrice");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsPriceGreaterThan(Double value) {
            addCriterion("buy_record_goods_price >", value, "buyRecordGoodsPrice");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("buy_record_goods_price >=", value, "buyRecordGoodsPrice");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsPriceLessThan(Double value) {
            addCriterion("buy_record_goods_price <", value, "buyRecordGoodsPrice");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsPriceLessThanOrEqualTo(Double value) {
            addCriterion("buy_record_goods_price <=", value, "buyRecordGoodsPrice");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsPriceIn(List<Double> values) {
            addCriterion("buy_record_goods_price in", values, "buyRecordGoodsPrice");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsPriceNotIn(List<Double> values) {
            addCriterion("buy_record_goods_price not in", values, "buyRecordGoodsPrice");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsPriceBetween(Double value1, Double value2) {
            addCriterion("buy_record_goods_price between", value1, value2, "buyRecordGoodsPrice");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsPriceNotBetween(Double value1, Double value2) {
            addCriterion("buy_record_goods_price not between", value1, value2, "buyRecordGoodsPrice");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsNumIsNull() {
            addCriterion("buy_record_goods_num is null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsNumIsNotNull() {
            addCriterion("buy_record_goods_num is not null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsNumEqualTo(Integer value) {
            addCriterion("buy_record_goods_num =", value, "buyRecordGoodsNum");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsNumNotEqualTo(Integer value) {
            addCriterion("buy_record_goods_num <>", value, "buyRecordGoodsNum");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsNumGreaterThan(Integer value) {
            addCriterion("buy_record_goods_num >", value, "buyRecordGoodsNum");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("buy_record_goods_num >=", value, "buyRecordGoodsNum");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsNumLessThan(Integer value) {
            addCriterion("buy_record_goods_num <", value, "buyRecordGoodsNum");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsNumLessThanOrEqualTo(Integer value) {
            addCriterion("buy_record_goods_num <=", value, "buyRecordGoodsNum");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsNumIn(List<Integer> values) {
            addCriterion("buy_record_goods_num in", values, "buyRecordGoodsNum");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsNumNotIn(List<Integer> values) {
            addCriterion("buy_record_goods_num not in", values, "buyRecordGoodsNum");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsNumBetween(Integer value1, Integer value2) {
            addCriterion("buy_record_goods_num between", value1, value2, "buyRecordGoodsNum");
            return (Criteria) this;
        }

        public Criteria andBuyRecordGoodsNumNotBetween(Integer value1, Integer value2) {
            addCriterion("buy_record_goods_num not between", value1, value2, "buyRecordGoodsNum");
            return (Criteria) this;
        }

        public Criteria andBuyRecordAddressIsNull() {
            addCriterion("buy_record_address is null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordAddressIsNotNull() {
            addCriterion("buy_record_address is not null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordAddressEqualTo(String value) {
            addCriterion("buy_record_address =", value, "buyRecordAddress");
            return (Criteria) this;
        }

        public Criteria andBuyRecordAddressNotEqualTo(String value) {
            addCriterion("buy_record_address <>", value, "buyRecordAddress");
            return (Criteria) this;
        }

        public Criteria andBuyRecordAddressGreaterThan(String value) {
            addCriterion("buy_record_address >", value, "buyRecordAddress");
            return (Criteria) this;
        }

        public Criteria andBuyRecordAddressGreaterThanOrEqualTo(String value) {
            addCriterion("buy_record_address >=", value, "buyRecordAddress");
            return (Criteria) this;
        }

        public Criteria andBuyRecordAddressLessThan(String value) {
            addCriterion("buy_record_address <", value, "buyRecordAddress");
            return (Criteria) this;
        }

        public Criteria andBuyRecordAddressLessThanOrEqualTo(String value) {
            addCriterion("buy_record_address <=", value, "buyRecordAddress");
            return (Criteria) this;
        }

        public Criteria andBuyRecordAddressLike(String value) {
            addCriterion("buy_record_address like", value, "buyRecordAddress");
            return (Criteria) this;
        }

        public Criteria andBuyRecordAddressNotLike(String value) {
            addCriterion("buy_record_address not like", value, "buyRecordAddress");
            return (Criteria) this;
        }

        public Criteria andBuyRecordAddressIn(List<String> values) {
            addCriterion("buy_record_address in", values, "buyRecordAddress");
            return (Criteria) this;
        }

        public Criteria andBuyRecordAddressNotIn(List<String> values) {
            addCriterion("buy_record_address not in", values, "buyRecordAddress");
            return (Criteria) this;
        }

        public Criteria andBuyRecordAddressBetween(String value1, String value2) {
            addCriterion("buy_record_address between", value1, value2, "buyRecordAddress");
            return (Criteria) this;
        }

        public Criteria andBuyRecordAddressNotBetween(String value1, String value2) {
            addCriterion("buy_record_address not between", value1, value2, "buyRecordAddress");
            return (Criteria) this;
        }

        public Criteria andBuyRecordStatusIsNull() {
            addCriterion("buy_record_status is null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordStatusIsNotNull() {
            addCriterion("buy_record_status is not null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordStatusEqualTo(Integer value) {
            addCriterion("buy_record_status =", value, "buyRecordStatus");
            return (Criteria) this;
        }

        public Criteria andBuyRecordStatusNotEqualTo(Integer value) {
            addCriterion("buy_record_status <>", value, "buyRecordStatus");
            return (Criteria) this;
        }

        public Criteria andBuyRecordStatusGreaterThan(Integer value) {
            addCriterion("buy_record_status >", value, "buyRecordStatus");
            return (Criteria) this;
        }

        public Criteria andBuyRecordStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("buy_record_status >=", value, "buyRecordStatus");
            return (Criteria) this;
        }

        public Criteria andBuyRecordStatusLessThan(Integer value) {
            addCriterion("buy_record_status <", value, "buyRecordStatus");
            return (Criteria) this;
        }

        public Criteria andBuyRecordStatusLessThanOrEqualTo(Integer value) {
            addCriterion("buy_record_status <=", value, "buyRecordStatus");
            return (Criteria) this;
        }

        public Criteria andBuyRecordStatusIn(List<Integer> values) {
            addCriterion("buy_record_status in", values, "buyRecordStatus");
            return (Criteria) this;
        }

        public Criteria andBuyRecordStatusNotIn(List<Integer> values) {
            addCriterion("buy_record_status not in", values, "buyRecordStatus");
            return (Criteria) this;
        }

        public Criteria andBuyRecordStatusBetween(Integer value1, Integer value2) {
            addCriterion("buy_record_status between", value1, value2, "buyRecordStatus");
            return (Criteria) this;
        }

        public Criteria andBuyRecordStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("buy_record_status not between", value1, value2, "buyRecordStatus");
            return (Criteria) this;
        }

        public Criteria andBuyRecordTimeIsNull() {
            addCriterion("buy_record_time is null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordTimeIsNotNull() {
            addCriterion("buy_record_time is not null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordTimeEqualTo(Date value) {
            addCriterion("buy_record_time =", value, "buyRecordTime");
            return (Criteria) this;
        }

        public Criteria andBuyRecordTimeNotEqualTo(Date value) {
            addCriterion("buy_record_time <>", value, "buyRecordTime");
            return (Criteria) this;
        }

        public Criteria andBuyRecordTimeGreaterThan(Date value) {
            addCriterion("buy_record_time >", value, "buyRecordTime");
            return (Criteria) this;
        }

        public Criteria andBuyRecordTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("buy_record_time >=", value, "buyRecordTime");
            return (Criteria) this;
        }

        public Criteria andBuyRecordTimeLessThan(Date value) {
            addCriterion("buy_record_time <", value, "buyRecordTime");
            return (Criteria) this;
        }

        public Criteria andBuyRecordTimeLessThanOrEqualTo(Date value) {
            addCriterion("buy_record_time <=", value, "buyRecordTime");
            return (Criteria) this;
        }

        public Criteria andBuyRecordTimeIn(List<Date> values) {
            addCriterion("buy_record_time in", values, "buyRecordTime");
            return (Criteria) this;
        }

        public Criteria andBuyRecordTimeNotIn(List<Date> values) {
            addCriterion("buy_record_time not in", values, "buyRecordTime");
            return (Criteria) this;
        }

        public Criteria andBuyRecordTimeBetween(Date value1, Date value2) {
            addCriterion("buy_record_time between", value1, value2, "buyRecordTime");
            return (Criteria) this;
        }

        public Criteria andBuyRecordTimeNotBetween(Date value1, Date value2) {
            addCriterion("buy_record_time not between", value1, value2, "buyRecordTime");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverNameIsNull() {
            addCriterion("buy_record_receiver_name is null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverNameIsNotNull() {
            addCriterion("buy_record_receiver_name is not null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverNameEqualTo(String value) {
            addCriterion("buy_record_receiver_name =", value, "buyRecordReceiverName");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverNameNotEqualTo(String value) {
            addCriterion("buy_record_receiver_name <>", value, "buyRecordReceiverName");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverNameGreaterThan(String value) {
            addCriterion("buy_record_receiver_name >", value, "buyRecordReceiverName");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverNameGreaterThanOrEqualTo(String value) {
            addCriterion("buy_record_receiver_name >=", value, "buyRecordReceiverName");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverNameLessThan(String value) {
            addCriterion("buy_record_receiver_name <", value, "buyRecordReceiverName");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverNameLessThanOrEqualTo(String value) {
            addCriterion("buy_record_receiver_name <=", value, "buyRecordReceiverName");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverNameLike(String value) {
            addCriterion("buy_record_receiver_name like", value, "buyRecordReceiverName");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverNameNotLike(String value) {
            addCriterion("buy_record_receiver_name not like", value, "buyRecordReceiverName");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverNameIn(List<String> values) {
            addCriterion("buy_record_receiver_name in", values, "buyRecordReceiverName");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverNameNotIn(List<String> values) {
            addCriterion("buy_record_receiver_name not in", values, "buyRecordReceiverName");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverNameBetween(String value1, String value2) {
            addCriterion("buy_record_receiver_name between", value1, value2, "buyRecordReceiverName");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverNameNotBetween(String value1, String value2) {
            addCriterion("buy_record_receiver_name not between", value1, value2, "buyRecordReceiverName");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverPhoneIsNull() {
            addCriterion("buy_record_receiver_phone is null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverPhoneIsNotNull() {
            addCriterion("buy_record_receiver_phone is not null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverPhoneEqualTo(String value) {
            addCriterion("buy_record_receiver_phone =", value, "buyRecordReceiverPhone");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverPhoneNotEqualTo(String value) {
            addCriterion("buy_record_receiver_phone <>", value, "buyRecordReceiverPhone");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverPhoneGreaterThan(String value) {
            addCriterion("buy_record_receiver_phone >", value, "buyRecordReceiverPhone");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("buy_record_receiver_phone >=", value, "buyRecordReceiverPhone");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverPhoneLessThan(String value) {
            addCriterion("buy_record_receiver_phone <", value, "buyRecordReceiverPhone");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverPhoneLessThanOrEqualTo(String value) {
            addCriterion("buy_record_receiver_phone <=", value, "buyRecordReceiverPhone");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverPhoneLike(String value) {
            addCriterion("buy_record_receiver_phone like", value, "buyRecordReceiverPhone");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverPhoneNotLike(String value) {
            addCriterion("buy_record_receiver_phone not like", value, "buyRecordReceiverPhone");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverPhoneIn(List<String> values) {
            addCriterion("buy_record_receiver_phone in", values, "buyRecordReceiverPhone");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverPhoneNotIn(List<String> values) {
            addCriterion("buy_record_receiver_phone not in", values, "buyRecordReceiverPhone");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverPhoneBetween(String value1, String value2) {
            addCriterion("buy_record_receiver_phone between", value1, value2, "buyRecordReceiverPhone");
            return (Criteria) this;
        }

        public Criteria andBuyRecordReceiverPhoneNotBetween(String value1, String value2) {
            addCriterion("buy_record_receiver_phone not between", value1, value2, "buyRecordReceiverPhone");
            return (Criteria) this;
        }

        public Criteria andBuyRecordIndexIsNull() {
            addCriterion("buy_record_index is null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordIndexIsNotNull() {
            addCriterion("buy_record_index is not null");
            return (Criteria) this;
        }

        public Criteria andBuyRecordIndexEqualTo(String value) {
            addCriterion("buy_record_index =", value, "buyRecordIndex");
            return (Criteria) this;
        }

        public Criteria andBuyRecordIndexNotEqualTo(String value) {
            addCriterion("buy_record_index <>", value, "buyRecordIndex");
            return (Criteria) this;
        }

        public Criteria andBuyRecordIndexGreaterThan(String value) {
            addCriterion("buy_record_index >", value, "buyRecordIndex");
            return (Criteria) this;
        }

        public Criteria andBuyRecordIndexGreaterThanOrEqualTo(String value) {
            addCriterion("buy_record_index >=", value, "buyRecordIndex");
            return (Criteria) this;
        }

        public Criteria andBuyRecordIndexLessThan(String value) {
            addCriterion("buy_record_index <", value, "buyRecordIndex");
            return (Criteria) this;
        }

        public Criteria andBuyRecordIndexLessThanOrEqualTo(String value) {
            addCriterion("buy_record_index <=", value, "buyRecordIndex");
            return (Criteria) this;
        }

        public Criteria andBuyRecordIndexLike(String value) {
            addCriterion("buy_record_index like", value, "buyRecordIndex");
            return (Criteria) this;
        }

        public Criteria andBuyRecordIndexNotLike(String value) {
            addCriterion("buy_record_index not like", value, "buyRecordIndex");
            return (Criteria) this;
        }

        public Criteria andBuyRecordIndexIn(List<String> values) {
            addCriterion("buy_record_index in", values, "buyRecordIndex");
            return (Criteria) this;
        }

        public Criteria andBuyRecordIndexNotIn(List<String> values) {
            addCriterion("buy_record_index not in", values, "buyRecordIndex");
            return (Criteria) this;
        }

        public Criteria andBuyRecordIndexBetween(String value1, String value2) {
            addCriterion("buy_record_index between", value1, value2, "buyRecordIndex");
            return (Criteria) this;
        }

        public Criteria andBuyRecordIndexNotBetween(String value1, String value2) {
            addCriterion("buy_record_index not between", value1, value2, "buyRecordIndex");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table buy_record
     *
     * @mbggenerated do_not_delete_during_merge Wed Oct 24 01:45:54 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table buy_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}