package com.judge.demo.Entity;

import java.io.Serializable;
import java.util.Date;

public class PersonRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_record.p_id
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private Long pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_record.p_name
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private String pName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_record.p_identity
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private String pIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_record.p_residence
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private String pResidence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_record.p_email
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private String pEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_record.p_phone
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private String pPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_record.p_weixin_id
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private String pWeixinId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_record.p_weixin
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private String pWeixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_record.p_qq
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private String pQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_record.p_zhifubao
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private String pZhifubao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_record.p_remark
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private String pRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_record.p_yuanding_grade
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private String pYuandingGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_record.p_yuanding_uid
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private String pYuandingUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_record.p_yuanding_name
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private String pYuandingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_record.p_yuanding_friend_num
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private Integer pYuandingFriendNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_record.p_yuanding_album_num
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private Integer pYuandingAlbumNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_record.p_yuanding_post_num
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private Integer pYuandingPostNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_record.p_yuanding_topic_num
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private Integer pYuandingTopicNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_record.p_yuanding_regist_ip
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private String pYuandingRegistIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_record.p_yuanding_regist_time
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private Date pYuandingRegistTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_record.p_yuanding_login_last_ip
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private String pYuandingLoginLastIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_record.p_yuanding_login_last_address
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private String pYuandingLoginLastAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_record.p_yuanding_login_last_time
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private Date pYuandingLoginLastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_record.p_address_info
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private String pAddressInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_record.p_trajectory_info
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private String pTrajectoryInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_record.p_evidence
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private String pEvidence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_record.p_id
     *
     * @return the value of person_record.p_id
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public Long getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_record.p_id
     *
     * @param pId the value for person_record.p_id
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setpId(Long pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_record.p_name
     *
     * @return the value of person_record.p_name
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_record.p_name
     *
     * @param pName the value for person_record.p_name
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_record.p_identity
     *
     * @return the value of person_record.p_identity
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public String getpIdentity() {
        return pIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_record.p_identity
     *
     * @param pIdentity the value for person_record.p_identity
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setpIdentity(String pIdentity) {
        this.pIdentity = pIdentity == null ? null : pIdentity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_record.p_residence
     *
     * @return the value of person_record.p_residence
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public String getpResidence() {
        return pResidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_record.p_residence
     *
     * @param pResidence the value for person_record.p_residence
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setpResidence(String pResidence) {
        this.pResidence = pResidence == null ? null : pResidence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_record.p_email
     *
     * @return the value of person_record.p_email
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public String getpEmail() {
        return pEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_record.p_email
     *
     * @param pEmail the value for person_record.p_email
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setpEmail(String pEmail) {
        this.pEmail = pEmail == null ? null : pEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_record.p_phone
     *
     * @return the value of person_record.p_phone
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public String getpPhone() {
        return pPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_record.p_phone
     *
     * @param pPhone the value for person_record.p_phone
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setpPhone(String pPhone) {
        this.pPhone = pPhone == null ? null : pPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_record.p_weixin_id
     *
     * @return the value of person_record.p_weixin_id
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public String getpWeixinId() {
        return pWeixinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_record.p_weixin_id
     *
     * @param pWeixinId the value for person_record.p_weixin_id
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setpWeixinId(String pWeixinId) {
        this.pWeixinId = pWeixinId == null ? null : pWeixinId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_record.p_weixin
     *
     * @return the value of person_record.p_weixin
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public String getpWeixin() {
        return pWeixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_record.p_weixin
     *
     * @param pWeixin the value for person_record.p_weixin
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setpWeixin(String pWeixin) {
        this.pWeixin = pWeixin == null ? null : pWeixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_record.p_qq
     *
     * @return the value of person_record.p_qq
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public String getpQq() {
        return pQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_record.p_qq
     *
     * @param pQq the value for person_record.p_qq
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setpQq(String pQq) {
        this.pQq = pQq == null ? null : pQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_record.p_zhifubao
     *
     * @return the value of person_record.p_zhifubao
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public String getpZhifubao() {
        return pZhifubao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_record.p_zhifubao
     *
     * @param pZhifubao the value for person_record.p_zhifubao
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setpZhifubao(String pZhifubao) {
        this.pZhifubao = pZhifubao == null ? null : pZhifubao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_record.p_remark
     *
     * @return the value of person_record.p_remark
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public String getpRemark() {
        return pRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_record.p_remark
     *
     * @param pRemark the value for person_record.p_remark
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setpRemark(String pRemark) {
        this.pRemark = pRemark == null ? null : pRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_record.p_yuanding_grade
     *
     * @return the value of person_record.p_yuanding_grade
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public String getpYuandingGrade() {
        return pYuandingGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_record.p_yuanding_grade
     *
     * @param pYuandingGrade the value for person_record.p_yuanding_grade
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setpYuandingGrade(String pYuandingGrade) {
        this.pYuandingGrade = pYuandingGrade == null ? null : pYuandingGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_record.p_yuanding_uid
     *
     * @return the value of person_record.p_yuanding_uid
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public String getpYuandingUid() {
        return pYuandingUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_record.p_yuanding_uid
     *
     * @param pYuandingUid the value for person_record.p_yuanding_uid
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setpYuandingUid(String pYuandingUid) {
        this.pYuandingUid = pYuandingUid == null ? null : pYuandingUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_record.p_yuanding_name
     *
     * @return the value of person_record.p_yuanding_name
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public String getpYuandingName() {
        return pYuandingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_record.p_yuanding_name
     *
     * @param pYuandingName the value for person_record.p_yuanding_name
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setpYuandingName(String pYuandingName) {
        this.pYuandingName = pYuandingName == null ? null : pYuandingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_record.p_yuanding_friend_num
     *
     * @return the value of person_record.p_yuanding_friend_num
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public Integer getpYuandingFriendNum() {
        return pYuandingFriendNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_record.p_yuanding_friend_num
     *
     * @param pYuandingFriendNum the value for person_record.p_yuanding_friend_num
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setpYuandingFriendNum(Integer pYuandingFriendNum) {
        this.pYuandingFriendNum = pYuandingFriendNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_record.p_yuanding_album_num
     *
     * @return the value of person_record.p_yuanding_album_num
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public Integer getpYuandingAlbumNum() {
        return pYuandingAlbumNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_record.p_yuanding_album_num
     *
     * @param pYuandingAlbumNum the value for person_record.p_yuanding_album_num
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setpYuandingAlbumNum(Integer pYuandingAlbumNum) {
        this.pYuandingAlbumNum = pYuandingAlbumNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_record.p_yuanding_post_num
     *
     * @return the value of person_record.p_yuanding_post_num
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public Integer getpYuandingPostNum() {
        return pYuandingPostNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_record.p_yuanding_post_num
     *
     * @param pYuandingPostNum the value for person_record.p_yuanding_post_num
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setpYuandingPostNum(Integer pYuandingPostNum) {
        this.pYuandingPostNum = pYuandingPostNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_record.p_yuanding_topic_num
     *
     * @return the value of person_record.p_yuanding_topic_num
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public Integer getpYuandingTopicNum() {
        return pYuandingTopicNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_record.p_yuanding_topic_num
     *
     * @param pYuandingTopicNum the value for person_record.p_yuanding_topic_num
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setpYuandingTopicNum(Integer pYuandingTopicNum) {
        this.pYuandingTopicNum = pYuandingTopicNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_record.p_yuanding_regist_ip
     *
     * @return the value of person_record.p_yuanding_regist_ip
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public String getpYuandingRegistIp() {
        return pYuandingRegistIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_record.p_yuanding_regist_ip
     *
     * @param pYuandingRegistIp the value for person_record.p_yuanding_regist_ip
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setpYuandingRegistIp(String pYuandingRegistIp) {
        this.pYuandingRegistIp = pYuandingRegistIp == null ? null : pYuandingRegistIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_record.p_yuanding_regist_time
     *
     * @return the value of person_record.p_yuanding_regist_time
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public Date getpYuandingRegistTime() {
        return pYuandingRegistTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_record.p_yuanding_regist_time
     *
     * @param pYuandingRegistTime the value for person_record.p_yuanding_regist_time
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setpYuandingRegistTime(Date pYuandingRegistTime) {
        this.pYuandingRegistTime = pYuandingRegistTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_record.p_yuanding_login_last_ip
     *
     * @return the value of person_record.p_yuanding_login_last_ip
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public String getpYuandingLoginLastIp() {
        return pYuandingLoginLastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_record.p_yuanding_login_last_ip
     *
     * @param pYuandingLoginLastIp the value for person_record.p_yuanding_login_last_ip
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setpYuandingLoginLastIp(String pYuandingLoginLastIp) {
        this.pYuandingLoginLastIp = pYuandingLoginLastIp == null ? null : pYuandingLoginLastIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_record.p_yuanding_login_last_address
     *
     * @return the value of person_record.p_yuanding_login_last_address
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public String getpYuandingLoginLastAddress() {
        return pYuandingLoginLastAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_record.p_yuanding_login_last_address
     *
     * @param pYuandingLoginLastAddress the value for person_record.p_yuanding_login_last_address
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setpYuandingLoginLastAddress(String pYuandingLoginLastAddress) {
        this.pYuandingLoginLastAddress = pYuandingLoginLastAddress == null ? null : pYuandingLoginLastAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_record.p_yuanding_login_last_time
     *
     * @return the value of person_record.p_yuanding_login_last_time
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public Date getpYuandingLoginLastTime() {
        return pYuandingLoginLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_record.p_yuanding_login_last_time
     *
     * @param pYuandingLoginLastTime the value for person_record.p_yuanding_login_last_time
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setpYuandingLoginLastTime(Date pYuandingLoginLastTime) {
        this.pYuandingLoginLastTime = pYuandingLoginLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_record.p_address_info
     *
     * @return the value of person_record.p_address_info
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public String getpAddressInfo() {
        return pAddressInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_record.p_address_info
     *
     * @param pAddressInfo the value for person_record.p_address_info
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setpAddressInfo(String pAddressInfo) {
        this.pAddressInfo = pAddressInfo == null ? null : pAddressInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_record.p_trajectory_info
     *
     * @return the value of person_record.p_trajectory_info
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public String getpTrajectoryInfo() {
        return pTrajectoryInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_record.p_trajectory_info
     *
     * @param pTrajectoryInfo the value for person_record.p_trajectory_info
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setpTrajectoryInfo(String pTrajectoryInfo) {
        this.pTrajectoryInfo = pTrajectoryInfo == null ? null : pTrajectoryInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_record.p_evidence
     *
     * @return the value of person_record.p_evidence
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public String getpEvidence() {
        return pEvidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_record.p_evidence
     *
     * @param pEvidence the value for person_record.p_evidence
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setpEvidence(String pEvidence) {
        this.pEvidence = pEvidence == null ? null : pEvidence.trim();
    }
}