package com.judge.demo.Entity;

import java.io.Serializable;
import java.util.List;
import java.util.Map;

public class Person implements Serializable {
    public static List<String> memory;
    public static int flag = 1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.person_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private Long personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.person_sender_zhifubao_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String personSenderZhifubaoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.person_sender_name
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String personSenderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.person_all
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String personAll;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table person
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.person_id
     *
     * @return the value of person.person_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.person_id
     *
     * @param personId the value for person.person_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.person_sender_zhifubao_id
     *
     * @return the value of person.person_sender_zhifubao_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getPersonSenderZhifubaoId() {
        return personSenderZhifubaoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.person_sender_zhifubao_id
     *
     * @param personSenderZhifubaoId the value for person.person_sender_zhifubao_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setPersonSenderZhifubaoId(String personSenderZhifubaoId) {
        this.personSenderZhifubaoId = personSenderZhifubaoId == null ? null : personSenderZhifubaoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.person_sender_name
     *
     * @return the value of person.person_sender_name
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getPersonSenderName() {
        return personSenderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.person_sender_name
     *
     * @param personSenderName the value for person.person_sender_name
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setPersonSenderName(String personSenderName) {
        this.personSenderName = personSenderName == null ? null : personSenderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.person_all
     *
     * @return the value of person.person_all
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getPersonAll() {
        return personAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.person_all
     *
     * @param personAll the value for person.person_all
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setPersonAll(String personAll) {
        this.personAll = personAll == null ? null : personAll.trim();
    }
}