package com.judge.demo.Entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PersonRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public PersonRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPIdIsNull() {
            addCriterion("p_id is null");
            return (Criteria) this;
        }

        public Criteria andPIdIsNotNull() {
            addCriterion("p_id is not null");
            return (Criteria) this;
        }

        public Criteria andPIdEqualTo(Long value) {
            addCriterion("p_id =", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdNotEqualTo(Long value) {
            addCriterion("p_id <>", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdGreaterThan(Long value) {
            addCriterion("p_id >", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdGreaterThanOrEqualTo(Long value) {
            addCriterion("p_id >=", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdLessThan(Long value) {
            addCriterion("p_id <", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdLessThanOrEqualTo(Long value) {
            addCriterion("p_id <=", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdIn(List<Long> values) {
            addCriterion("p_id in", values, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdNotIn(List<Long> values) {
            addCriterion("p_id not in", values, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdBetween(Long value1, Long value2) {
            addCriterion("p_id between", value1, value2, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdNotBetween(Long value1, Long value2) {
            addCriterion("p_id not between", value1, value2, "pId");
            return (Criteria) this;
        }

        public Criteria andPNameIsNull() {
            addCriterion("p_name is null");
            return (Criteria) this;
        }

        public Criteria andPNameIsNotNull() {
            addCriterion("p_name is not null");
            return (Criteria) this;
        }

        public Criteria andPNameEqualTo(String value) {
            addCriterion("p_name =", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotEqualTo(String value) {
            addCriterion("p_name <>", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameGreaterThan(String value) {
            addCriterion("p_name >", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameGreaterThanOrEqualTo(String value) {
            addCriterion("p_name >=", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameLessThan(String value) {
            addCriterion("p_name <", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameLessThanOrEqualTo(String value) {
            addCriterion("p_name <=", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameLike(String value) {
            addCriterion("p_name like", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotLike(String value) {
            addCriterion("p_name not like", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameIn(List<String> values) {
            addCriterion("p_name in", values, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotIn(List<String> values) {
            addCriterion("p_name not in", values, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameBetween(String value1, String value2) {
            addCriterion("p_name between", value1, value2, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotBetween(String value1, String value2) {
            addCriterion("p_name not between", value1, value2, "pName");
            return (Criteria) this;
        }

        public Criteria andPIdentityIsNull() {
            addCriterion("p_identity is null");
            return (Criteria) this;
        }

        public Criteria andPIdentityIsNotNull() {
            addCriterion("p_identity is not null");
            return (Criteria) this;
        }

        public Criteria andPIdentityEqualTo(String value) {
            addCriterion("p_identity =", value, "pIdentity");
            return (Criteria) this;
        }

        public Criteria andPIdentityNotEqualTo(String value) {
            addCriterion("p_identity <>", value, "pIdentity");
            return (Criteria) this;
        }

        public Criteria andPIdentityGreaterThan(String value) {
            addCriterion("p_identity >", value, "pIdentity");
            return (Criteria) this;
        }

        public Criteria andPIdentityGreaterThanOrEqualTo(String value) {
            addCriterion("p_identity >=", value, "pIdentity");
            return (Criteria) this;
        }

        public Criteria andPIdentityLessThan(String value) {
            addCriterion("p_identity <", value, "pIdentity");
            return (Criteria) this;
        }

        public Criteria andPIdentityLessThanOrEqualTo(String value) {
            addCriterion("p_identity <=", value, "pIdentity");
            return (Criteria) this;
        }

        public Criteria andPIdentityLike(String value) {
            addCriterion("p_identity like", value, "pIdentity");
            return (Criteria) this;
        }

        public Criteria andPIdentityNotLike(String value) {
            addCriterion("p_identity not like", value, "pIdentity");
            return (Criteria) this;
        }

        public Criteria andPIdentityIn(List<String> values) {
            addCriterion("p_identity in", values, "pIdentity");
            return (Criteria) this;
        }

        public Criteria andPIdentityNotIn(List<String> values) {
            addCriterion("p_identity not in", values, "pIdentity");
            return (Criteria) this;
        }

        public Criteria andPIdentityBetween(String value1, String value2) {
            addCriterion("p_identity between", value1, value2, "pIdentity");
            return (Criteria) this;
        }

        public Criteria andPIdentityNotBetween(String value1, String value2) {
            addCriterion("p_identity not between", value1, value2, "pIdentity");
            return (Criteria) this;
        }

        public Criteria andPResidenceIsNull() {
            addCriterion("p_residence is null");
            return (Criteria) this;
        }

        public Criteria andPResidenceIsNotNull() {
            addCriterion("p_residence is not null");
            return (Criteria) this;
        }

        public Criteria andPResidenceEqualTo(String value) {
            addCriterion("p_residence =", value, "pResidence");
            return (Criteria) this;
        }

        public Criteria andPResidenceNotEqualTo(String value) {
            addCriterion("p_residence <>", value, "pResidence");
            return (Criteria) this;
        }

        public Criteria andPResidenceGreaterThan(String value) {
            addCriterion("p_residence >", value, "pResidence");
            return (Criteria) this;
        }

        public Criteria andPResidenceGreaterThanOrEqualTo(String value) {
            addCriterion("p_residence >=", value, "pResidence");
            return (Criteria) this;
        }

        public Criteria andPResidenceLessThan(String value) {
            addCriterion("p_residence <", value, "pResidence");
            return (Criteria) this;
        }

        public Criteria andPResidenceLessThanOrEqualTo(String value) {
            addCriterion("p_residence <=", value, "pResidence");
            return (Criteria) this;
        }

        public Criteria andPResidenceLike(String value) {
            addCriterion("p_residence like", value, "pResidence");
            return (Criteria) this;
        }

        public Criteria andPResidenceNotLike(String value) {
            addCriterion("p_residence not like", value, "pResidence");
            return (Criteria) this;
        }

        public Criteria andPResidenceIn(List<String> values) {
            addCriterion("p_residence in", values, "pResidence");
            return (Criteria) this;
        }

        public Criteria andPResidenceNotIn(List<String> values) {
            addCriterion("p_residence not in", values, "pResidence");
            return (Criteria) this;
        }

        public Criteria andPResidenceBetween(String value1, String value2) {
            addCriterion("p_residence between", value1, value2, "pResidence");
            return (Criteria) this;
        }

        public Criteria andPResidenceNotBetween(String value1, String value2) {
            addCriterion("p_residence not between", value1, value2, "pResidence");
            return (Criteria) this;
        }

        public Criteria andPEmailIsNull() {
            addCriterion("p_email is null");
            return (Criteria) this;
        }

        public Criteria andPEmailIsNotNull() {
            addCriterion("p_email is not null");
            return (Criteria) this;
        }

        public Criteria andPEmailEqualTo(String value) {
            addCriterion("p_email =", value, "pEmail");
            return (Criteria) this;
        }

        public Criteria andPEmailNotEqualTo(String value) {
            addCriterion("p_email <>", value, "pEmail");
            return (Criteria) this;
        }

        public Criteria andPEmailGreaterThan(String value) {
            addCriterion("p_email >", value, "pEmail");
            return (Criteria) this;
        }

        public Criteria andPEmailGreaterThanOrEqualTo(String value) {
            addCriterion("p_email >=", value, "pEmail");
            return (Criteria) this;
        }

        public Criteria andPEmailLessThan(String value) {
            addCriterion("p_email <", value, "pEmail");
            return (Criteria) this;
        }

        public Criteria andPEmailLessThanOrEqualTo(String value) {
            addCriterion("p_email <=", value, "pEmail");
            return (Criteria) this;
        }

        public Criteria andPEmailLike(String value) {
            addCriterion("p_email like", value, "pEmail");
            return (Criteria) this;
        }

        public Criteria andPEmailNotLike(String value) {
            addCriterion("p_email not like", value, "pEmail");
            return (Criteria) this;
        }

        public Criteria andPEmailIn(List<String> values) {
            addCriterion("p_email in", values, "pEmail");
            return (Criteria) this;
        }

        public Criteria andPEmailNotIn(List<String> values) {
            addCriterion("p_email not in", values, "pEmail");
            return (Criteria) this;
        }

        public Criteria andPEmailBetween(String value1, String value2) {
            addCriterion("p_email between", value1, value2, "pEmail");
            return (Criteria) this;
        }

        public Criteria andPEmailNotBetween(String value1, String value2) {
            addCriterion("p_email not between", value1, value2, "pEmail");
            return (Criteria) this;
        }

        public Criteria andPPhoneIsNull() {
            addCriterion("p_phone is null");
            return (Criteria) this;
        }

        public Criteria andPPhoneIsNotNull() {
            addCriterion("p_phone is not null");
            return (Criteria) this;
        }

        public Criteria andPPhoneEqualTo(String value) {
            addCriterion("p_phone =", value, "pPhone");
            return (Criteria) this;
        }

        public Criteria andPPhoneNotEqualTo(String value) {
            addCriterion("p_phone <>", value, "pPhone");
            return (Criteria) this;
        }

        public Criteria andPPhoneGreaterThan(String value) {
            addCriterion("p_phone >", value, "pPhone");
            return (Criteria) this;
        }

        public Criteria andPPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("p_phone >=", value, "pPhone");
            return (Criteria) this;
        }

        public Criteria andPPhoneLessThan(String value) {
            addCriterion("p_phone <", value, "pPhone");
            return (Criteria) this;
        }

        public Criteria andPPhoneLessThanOrEqualTo(String value) {
            addCriterion("p_phone <=", value, "pPhone");
            return (Criteria) this;
        }

        public Criteria andPPhoneLike(String value) {
            addCriterion("p_phone like", value, "pPhone");
            return (Criteria) this;
        }

        public Criteria andPPhoneNotLike(String value) {
            addCriterion("p_phone not like", value, "pPhone");
            return (Criteria) this;
        }

        public Criteria andPPhoneIn(List<String> values) {
            addCriterion("p_phone in", values, "pPhone");
            return (Criteria) this;
        }

        public Criteria andPPhoneNotIn(List<String> values) {
            addCriterion("p_phone not in", values, "pPhone");
            return (Criteria) this;
        }

        public Criteria andPPhoneBetween(String value1, String value2) {
            addCriterion("p_phone between", value1, value2, "pPhone");
            return (Criteria) this;
        }

        public Criteria andPPhoneNotBetween(String value1, String value2) {
            addCriterion("p_phone not between", value1, value2, "pPhone");
            return (Criteria) this;
        }

        public Criteria andPWeixinIdIsNull() {
            addCriterion("p_weixin_id is null");
            return (Criteria) this;
        }

        public Criteria andPWeixinIdIsNotNull() {
            addCriterion("p_weixin_id is not null");
            return (Criteria) this;
        }

        public Criteria andPWeixinIdEqualTo(String value) {
            addCriterion("p_weixin_id =", value, "pWeixinId");
            return (Criteria) this;
        }

        public Criteria andPWeixinIdNotEqualTo(String value) {
            addCriterion("p_weixin_id <>", value, "pWeixinId");
            return (Criteria) this;
        }

        public Criteria andPWeixinIdGreaterThan(String value) {
            addCriterion("p_weixin_id >", value, "pWeixinId");
            return (Criteria) this;
        }

        public Criteria andPWeixinIdGreaterThanOrEqualTo(String value) {
            addCriterion("p_weixin_id >=", value, "pWeixinId");
            return (Criteria) this;
        }

        public Criteria andPWeixinIdLessThan(String value) {
            addCriterion("p_weixin_id <", value, "pWeixinId");
            return (Criteria) this;
        }

        public Criteria andPWeixinIdLessThanOrEqualTo(String value) {
            addCriterion("p_weixin_id <=", value, "pWeixinId");
            return (Criteria) this;
        }

        public Criteria andPWeixinIdLike(String value) {
            addCriterion("p_weixin_id like", value, "pWeixinId");
            return (Criteria) this;
        }

        public Criteria andPWeixinIdNotLike(String value) {
            addCriterion("p_weixin_id not like", value, "pWeixinId");
            return (Criteria) this;
        }

        public Criteria andPWeixinIdIn(List<String> values) {
            addCriterion("p_weixin_id in", values, "pWeixinId");
            return (Criteria) this;
        }

        public Criteria andPWeixinIdNotIn(List<String> values) {
            addCriterion("p_weixin_id not in", values, "pWeixinId");
            return (Criteria) this;
        }

        public Criteria andPWeixinIdBetween(String value1, String value2) {
            addCriterion("p_weixin_id between", value1, value2, "pWeixinId");
            return (Criteria) this;
        }

        public Criteria andPWeixinIdNotBetween(String value1, String value2) {
            addCriterion("p_weixin_id not between", value1, value2, "pWeixinId");
            return (Criteria) this;
        }

        public Criteria andPWeixinIsNull() {
            addCriterion("p_weixin is null");
            return (Criteria) this;
        }

        public Criteria andPWeixinIsNotNull() {
            addCriterion("p_weixin is not null");
            return (Criteria) this;
        }

        public Criteria andPWeixinEqualTo(String value) {
            addCriterion("p_weixin =", value, "pWeixin");
            return (Criteria) this;
        }

        public Criteria andPWeixinNotEqualTo(String value) {
            addCriterion("p_weixin <>", value, "pWeixin");
            return (Criteria) this;
        }

        public Criteria andPWeixinGreaterThan(String value) {
            addCriterion("p_weixin >", value, "pWeixin");
            return (Criteria) this;
        }

        public Criteria andPWeixinGreaterThanOrEqualTo(String value) {
            addCriterion("p_weixin >=", value, "pWeixin");
            return (Criteria) this;
        }

        public Criteria andPWeixinLessThan(String value) {
            addCriterion("p_weixin <", value, "pWeixin");
            return (Criteria) this;
        }

        public Criteria andPWeixinLessThanOrEqualTo(String value) {
            addCriterion("p_weixin <=", value, "pWeixin");
            return (Criteria) this;
        }

        public Criteria andPWeixinLike(String value) {
            addCriterion("p_weixin like", value, "pWeixin");
            return (Criteria) this;
        }

        public Criteria andPWeixinNotLike(String value) {
            addCriterion("p_weixin not like", value, "pWeixin");
            return (Criteria) this;
        }

        public Criteria andPWeixinIn(List<String> values) {
            addCriterion("p_weixin in", values, "pWeixin");
            return (Criteria) this;
        }

        public Criteria andPWeixinNotIn(List<String> values) {
            addCriterion("p_weixin not in", values, "pWeixin");
            return (Criteria) this;
        }

        public Criteria andPWeixinBetween(String value1, String value2) {
            addCriterion("p_weixin between", value1, value2, "pWeixin");
            return (Criteria) this;
        }

        public Criteria andPWeixinNotBetween(String value1, String value2) {
            addCriterion("p_weixin not between", value1, value2, "pWeixin");
            return (Criteria) this;
        }

        public Criteria andPQqIsNull() {
            addCriterion("p_qq is null");
            return (Criteria) this;
        }

        public Criteria andPQqIsNotNull() {
            addCriterion("p_qq is not null");
            return (Criteria) this;
        }

        public Criteria andPQqEqualTo(String value) {
            addCriterion("p_qq =", value, "pQq");
            return (Criteria) this;
        }

        public Criteria andPQqNotEqualTo(String value) {
            addCriterion("p_qq <>", value, "pQq");
            return (Criteria) this;
        }

        public Criteria andPQqGreaterThan(String value) {
            addCriterion("p_qq >", value, "pQq");
            return (Criteria) this;
        }

        public Criteria andPQqGreaterThanOrEqualTo(String value) {
            addCriterion("p_qq >=", value, "pQq");
            return (Criteria) this;
        }

        public Criteria andPQqLessThan(String value) {
            addCriterion("p_qq <", value, "pQq");
            return (Criteria) this;
        }

        public Criteria andPQqLessThanOrEqualTo(String value) {
            addCriterion("p_qq <=", value, "pQq");
            return (Criteria) this;
        }

        public Criteria andPQqLike(String value) {
            addCriterion("p_qq like", value, "pQq");
            return (Criteria) this;
        }

        public Criteria andPQqNotLike(String value) {
            addCriterion("p_qq not like", value, "pQq");
            return (Criteria) this;
        }

        public Criteria andPQqIn(List<String> values) {
            addCriterion("p_qq in", values, "pQq");
            return (Criteria) this;
        }

        public Criteria andPQqNotIn(List<String> values) {
            addCriterion("p_qq not in", values, "pQq");
            return (Criteria) this;
        }

        public Criteria andPQqBetween(String value1, String value2) {
            addCriterion("p_qq between", value1, value2, "pQq");
            return (Criteria) this;
        }

        public Criteria andPQqNotBetween(String value1, String value2) {
            addCriterion("p_qq not between", value1, value2, "pQq");
            return (Criteria) this;
        }

        public Criteria andPZhifubaoIsNull() {
            addCriterion("p_zhifubao is null");
            return (Criteria) this;
        }

        public Criteria andPZhifubaoIsNotNull() {
            addCriterion("p_zhifubao is not null");
            return (Criteria) this;
        }

        public Criteria andPZhifubaoEqualTo(String value) {
            addCriterion("p_zhifubao =", value, "pZhifubao");
            return (Criteria) this;
        }

        public Criteria andPZhifubaoNotEqualTo(String value) {
            addCriterion("p_zhifubao <>", value, "pZhifubao");
            return (Criteria) this;
        }

        public Criteria andPZhifubaoGreaterThan(String value) {
            addCriterion("p_zhifubao >", value, "pZhifubao");
            return (Criteria) this;
        }

        public Criteria andPZhifubaoGreaterThanOrEqualTo(String value) {
            addCriterion("p_zhifubao >=", value, "pZhifubao");
            return (Criteria) this;
        }

        public Criteria andPZhifubaoLessThan(String value) {
            addCriterion("p_zhifubao <", value, "pZhifubao");
            return (Criteria) this;
        }

        public Criteria andPZhifubaoLessThanOrEqualTo(String value) {
            addCriterion("p_zhifubao <=", value, "pZhifubao");
            return (Criteria) this;
        }

        public Criteria andPZhifubaoLike(String value) {
            addCriterion("p_zhifubao like", value, "pZhifubao");
            return (Criteria) this;
        }

        public Criteria andPZhifubaoNotLike(String value) {
            addCriterion("p_zhifubao not like", value, "pZhifubao");
            return (Criteria) this;
        }

        public Criteria andPZhifubaoIn(List<String> values) {
            addCriterion("p_zhifubao in", values, "pZhifubao");
            return (Criteria) this;
        }

        public Criteria andPZhifubaoNotIn(List<String> values) {
            addCriterion("p_zhifubao not in", values, "pZhifubao");
            return (Criteria) this;
        }

        public Criteria andPZhifubaoBetween(String value1, String value2) {
            addCriterion("p_zhifubao between", value1, value2, "pZhifubao");
            return (Criteria) this;
        }

        public Criteria andPZhifubaoNotBetween(String value1, String value2) {
            addCriterion("p_zhifubao not between", value1, value2, "pZhifubao");
            return (Criteria) this;
        }

        public Criteria andPRemarkIsNull() {
            addCriterion("p_remark is null");
            return (Criteria) this;
        }

        public Criteria andPRemarkIsNotNull() {
            addCriterion("p_remark is not null");
            return (Criteria) this;
        }

        public Criteria andPRemarkEqualTo(String value) {
            addCriterion("p_remark =", value, "pRemark");
            return (Criteria) this;
        }

        public Criteria andPRemarkNotEqualTo(String value) {
            addCriterion("p_remark <>", value, "pRemark");
            return (Criteria) this;
        }

        public Criteria andPRemarkGreaterThan(String value) {
            addCriterion("p_remark >", value, "pRemark");
            return (Criteria) this;
        }

        public Criteria andPRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("p_remark >=", value, "pRemark");
            return (Criteria) this;
        }

        public Criteria andPRemarkLessThan(String value) {
            addCriterion("p_remark <", value, "pRemark");
            return (Criteria) this;
        }

        public Criteria andPRemarkLessThanOrEqualTo(String value) {
            addCriterion("p_remark <=", value, "pRemark");
            return (Criteria) this;
        }

        public Criteria andPRemarkLike(String value) {
            addCriterion("p_remark like", value, "pRemark");
            return (Criteria) this;
        }

        public Criteria andPRemarkNotLike(String value) {
            addCriterion("p_remark not like", value, "pRemark");
            return (Criteria) this;
        }

        public Criteria andPRemarkIn(List<String> values) {
            addCriterion("p_remark in", values, "pRemark");
            return (Criteria) this;
        }

        public Criteria andPRemarkNotIn(List<String> values) {
            addCriterion("p_remark not in", values, "pRemark");
            return (Criteria) this;
        }

        public Criteria andPRemarkBetween(String value1, String value2) {
            addCriterion("p_remark between", value1, value2, "pRemark");
            return (Criteria) this;
        }

        public Criteria andPRemarkNotBetween(String value1, String value2) {
            addCriterion("p_remark not between", value1, value2, "pRemark");
            return (Criteria) this;
        }

        public Criteria andPYuandingGradeIsNull() {
            addCriterion("p_yuanding_grade is null");
            return (Criteria) this;
        }

        public Criteria andPYuandingGradeIsNotNull() {
            addCriterion("p_yuanding_grade is not null");
            return (Criteria) this;
        }

        public Criteria andPYuandingGradeEqualTo(String value) {
            addCriterion("p_yuanding_grade =", value, "pYuandingGrade");
            return (Criteria) this;
        }

        public Criteria andPYuandingGradeNotEqualTo(String value) {
            addCriterion("p_yuanding_grade <>", value, "pYuandingGrade");
            return (Criteria) this;
        }

        public Criteria andPYuandingGradeGreaterThan(String value) {
            addCriterion("p_yuanding_grade >", value, "pYuandingGrade");
            return (Criteria) this;
        }

        public Criteria andPYuandingGradeGreaterThanOrEqualTo(String value) {
            addCriterion("p_yuanding_grade >=", value, "pYuandingGrade");
            return (Criteria) this;
        }

        public Criteria andPYuandingGradeLessThan(String value) {
            addCriterion("p_yuanding_grade <", value, "pYuandingGrade");
            return (Criteria) this;
        }

        public Criteria andPYuandingGradeLessThanOrEqualTo(String value) {
            addCriterion("p_yuanding_grade <=", value, "pYuandingGrade");
            return (Criteria) this;
        }

        public Criteria andPYuandingGradeLike(String value) {
            addCriterion("p_yuanding_grade like", value, "pYuandingGrade");
            return (Criteria) this;
        }

        public Criteria andPYuandingGradeNotLike(String value) {
            addCriterion("p_yuanding_grade not like", value, "pYuandingGrade");
            return (Criteria) this;
        }

        public Criteria andPYuandingGradeIn(List<String> values) {
            addCriterion("p_yuanding_grade in", values, "pYuandingGrade");
            return (Criteria) this;
        }

        public Criteria andPYuandingGradeNotIn(List<String> values) {
            addCriterion("p_yuanding_grade not in", values, "pYuandingGrade");
            return (Criteria) this;
        }

        public Criteria andPYuandingGradeBetween(String value1, String value2) {
            addCriterion("p_yuanding_grade between", value1, value2, "pYuandingGrade");
            return (Criteria) this;
        }

        public Criteria andPYuandingGradeNotBetween(String value1, String value2) {
            addCriterion("p_yuanding_grade not between", value1, value2, "pYuandingGrade");
            return (Criteria) this;
        }

        public Criteria andPYuandingUidIsNull() {
            addCriterion("p_yuanding_uid is null");
            return (Criteria) this;
        }

        public Criteria andPYuandingUidIsNotNull() {
            addCriterion("p_yuanding_uid is not null");
            return (Criteria) this;
        }

        public Criteria andPYuandingUidEqualTo(String value) {
            addCriterion("p_yuanding_uid =", value, "pYuandingUid");
            return (Criteria) this;
        }

        public Criteria andPYuandingUidNotEqualTo(String value) {
            addCriterion("p_yuanding_uid <>", value, "pYuandingUid");
            return (Criteria) this;
        }

        public Criteria andPYuandingUidGreaterThan(String value) {
            addCriterion("p_yuanding_uid >", value, "pYuandingUid");
            return (Criteria) this;
        }

        public Criteria andPYuandingUidGreaterThanOrEqualTo(String value) {
            addCriterion("p_yuanding_uid >=", value, "pYuandingUid");
            return (Criteria) this;
        }

        public Criteria andPYuandingUidLessThan(String value) {
            addCriterion("p_yuanding_uid <", value, "pYuandingUid");
            return (Criteria) this;
        }

        public Criteria andPYuandingUidLessThanOrEqualTo(String value) {
            addCriterion("p_yuanding_uid <=", value, "pYuandingUid");
            return (Criteria) this;
        }

        public Criteria andPYuandingUidLike(String value) {
            addCriterion("p_yuanding_uid like", value, "pYuandingUid");
            return (Criteria) this;
        }

        public Criteria andPYuandingUidNotLike(String value) {
            addCriterion("p_yuanding_uid not like", value, "pYuandingUid");
            return (Criteria) this;
        }

        public Criteria andPYuandingUidIn(List<String> values) {
            addCriterion("p_yuanding_uid in", values, "pYuandingUid");
            return (Criteria) this;
        }

        public Criteria andPYuandingUidNotIn(List<String> values) {
            addCriterion("p_yuanding_uid not in", values, "pYuandingUid");
            return (Criteria) this;
        }

        public Criteria andPYuandingUidBetween(String value1, String value2) {
            addCriterion("p_yuanding_uid between", value1, value2, "pYuandingUid");
            return (Criteria) this;
        }

        public Criteria andPYuandingUidNotBetween(String value1, String value2) {
            addCriterion("p_yuanding_uid not between", value1, value2, "pYuandingUid");
            return (Criteria) this;
        }

        public Criteria andPYuandingNameIsNull() {
            addCriterion("p_yuanding_name is null");
            return (Criteria) this;
        }

        public Criteria andPYuandingNameIsNotNull() {
            addCriterion("p_yuanding_name is not null");
            return (Criteria) this;
        }

        public Criteria andPYuandingNameEqualTo(String value) {
            addCriterion("p_yuanding_name =", value, "pYuandingName");
            return (Criteria) this;
        }

        public Criteria andPYuandingNameNotEqualTo(String value) {
            addCriterion("p_yuanding_name <>", value, "pYuandingName");
            return (Criteria) this;
        }

        public Criteria andPYuandingNameGreaterThan(String value) {
            addCriterion("p_yuanding_name >", value, "pYuandingName");
            return (Criteria) this;
        }

        public Criteria andPYuandingNameGreaterThanOrEqualTo(String value) {
            addCriterion("p_yuanding_name >=", value, "pYuandingName");
            return (Criteria) this;
        }

        public Criteria andPYuandingNameLessThan(String value) {
            addCriterion("p_yuanding_name <", value, "pYuandingName");
            return (Criteria) this;
        }

        public Criteria andPYuandingNameLessThanOrEqualTo(String value) {
            addCriterion("p_yuanding_name <=", value, "pYuandingName");
            return (Criteria) this;
        }

        public Criteria andPYuandingNameLike(String value) {
            addCriterion("p_yuanding_name like", value, "pYuandingName");
            return (Criteria) this;
        }

        public Criteria andPYuandingNameNotLike(String value) {
            addCriterion("p_yuanding_name not like", value, "pYuandingName");
            return (Criteria) this;
        }

        public Criteria andPYuandingNameIn(List<String> values) {
            addCriterion("p_yuanding_name in", values, "pYuandingName");
            return (Criteria) this;
        }

        public Criteria andPYuandingNameNotIn(List<String> values) {
            addCriterion("p_yuanding_name not in", values, "pYuandingName");
            return (Criteria) this;
        }

        public Criteria andPYuandingNameBetween(String value1, String value2) {
            addCriterion("p_yuanding_name between", value1, value2, "pYuandingName");
            return (Criteria) this;
        }

        public Criteria andPYuandingNameNotBetween(String value1, String value2) {
            addCriterion("p_yuanding_name not between", value1, value2, "pYuandingName");
            return (Criteria) this;
        }

        public Criteria andPYuandingFriendNumIsNull() {
            addCriterion("p_yuanding_friend_num is null");
            return (Criteria) this;
        }

        public Criteria andPYuandingFriendNumIsNotNull() {
            addCriterion("p_yuanding_friend_num is not null");
            return (Criteria) this;
        }

        public Criteria andPYuandingFriendNumEqualTo(Integer value) {
            addCriterion("p_yuanding_friend_num =", value, "pYuandingFriendNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingFriendNumNotEqualTo(Integer value) {
            addCriterion("p_yuanding_friend_num <>", value, "pYuandingFriendNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingFriendNumGreaterThan(Integer value) {
            addCriterion("p_yuanding_friend_num >", value, "pYuandingFriendNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingFriendNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("p_yuanding_friend_num >=", value, "pYuandingFriendNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingFriendNumLessThan(Integer value) {
            addCriterion("p_yuanding_friend_num <", value, "pYuandingFriendNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingFriendNumLessThanOrEqualTo(Integer value) {
            addCriterion("p_yuanding_friend_num <=", value, "pYuandingFriendNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingFriendNumIn(List<Integer> values) {
            addCriterion("p_yuanding_friend_num in", values, "pYuandingFriendNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingFriendNumNotIn(List<Integer> values) {
            addCriterion("p_yuanding_friend_num not in", values, "pYuandingFriendNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingFriendNumBetween(Integer value1, Integer value2) {
            addCriterion("p_yuanding_friend_num between", value1, value2, "pYuandingFriendNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingFriendNumNotBetween(Integer value1, Integer value2) {
            addCriterion("p_yuanding_friend_num not between", value1, value2, "pYuandingFriendNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingAlbumNumIsNull() {
            addCriterion("p_yuanding_album_num is null");
            return (Criteria) this;
        }

        public Criteria andPYuandingAlbumNumIsNotNull() {
            addCriterion("p_yuanding_album_num is not null");
            return (Criteria) this;
        }

        public Criteria andPYuandingAlbumNumEqualTo(Integer value) {
            addCriterion("p_yuanding_album_num =", value, "pYuandingAlbumNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingAlbumNumNotEqualTo(Integer value) {
            addCriterion("p_yuanding_album_num <>", value, "pYuandingAlbumNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingAlbumNumGreaterThan(Integer value) {
            addCriterion("p_yuanding_album_num >", value, "pYuandingAlbumNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingAlbumNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("p_yuanding_album_num >=", value, "pYuandingAlbumNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingAlbumNumLessThan(Integer value) {
            addCriterion("p_yuanding_album_num <", value, "pYuandingAlbumNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingAlbumNumLessThanOrEqualTo(Integer value) {
            addCriterion("p_yuanding_album_num <=", value, "pYuandingAlbumNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingAlbumNumIn(List<Integer> values) {
            addCriterion("p_yuanding_album_num in", values, "pYuandingAlbumNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingAlbumNumNotIn(List<Integer> values) {
            addCriterion("p_yuanding_album_num not in", values, "pYuandingAlbumNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingAlbumNumBetween(Integer value1, Integer value2) {
            addCriterion("p_yuanding_album_num between", value1, value2, "pYuandingAlbumNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingAlbumNumNotBetween(Integer value1, Integer value2) {
            addCriterion("p_yuanding_album_num not between", value1, value2, "pYuandingAlbumNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingPostNumIsNull() {
            addCriterion("p_yuanding_post_num is null");
            return (Criteria) this;
        }

        public Criteria andPYuandingPostNumIsNotNull() {
            addCriterion("p_yuanding_post_num is not null");
            return (Criteria) this;
        }

        public Criteria andPYuandingPostNumEqualTo(Integer value) {
            addCriterion("p_yuanding_post_num =", value, "pYuandingPostNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingPostNumNotEqualTo(Integer value) {
            addCriterion("p_yuanding_post_num <>", value, "pYuandingPostNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingPostNumGreaterThan(Integer value) {
            addCriterion("p_yuanding_post_num >", value, "pYuandingPostNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingPostNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("p_yuanding_post_num >=", value, "pYuandingPostNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingPostNumLessThan(Integer value) {
            addCriterion("p_yuanding_post_num <", value, "pYuandingPostNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingPostNumLessThanOrEqualTo(Integer value) {
            addCriterion("p_yuanding_post_num <=", value, "pYuandingPostNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingPostNumIn(List<Integer> values) {
            addCriterion("p_yuanding_post_num in", values, "pYuandingPostNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingPostNumNotIn(List<Integer> values) {
            addCriterion("p_yuanding_post_num not in", values, "pYuandingPostNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingPostNumBetween(Integer value1, Integer value2) {
            addCriterion("p_yuanding_post_num between", value1, value2, "pYuandingPostNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingPostNumNotBetween(Integer value1, Integer value2) {
            addCriterion("p_yuanding_post_num not between", value1, value2, "pYuandingPostNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingTopicNumIsNull() {
            addCriterion("p_yuanding_topic_num is null");
            return (Criteria) this;
        }

        public Criteria andPYuandingTopicNumIsNotNull() {
            addCriterion("p_yuanding_topic_num is not null");
            return (Criteria) this;
        }

        public Criteria andPYuandingTopicNumEqualTo(Integer value) {
            addCriterion("p_yuanding_topic_num =", value, "pYuandingTopicNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingTopicNumNotEqualTo(Integer value) {
            addCriterion("p_yuanding_topic_num <>", value, "pYuandingTopicNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingTopicNumGreaterThan(Integer value) {
            addCriterion("p_yuanding_topic_num >", value, "pYuandingTopicNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingTopicNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("p_yuanding_topic_num >=", value, "pYuandingTopicNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingTopicNumLessThan(Integer value) {
            addCriterion("p_yuanding_topic_num <", value, "pYuandingTopicNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingTopicNumLessThanOrEqualTo(Integer value) {
            addCriterion("p_yuanding_topic_num <=", value, "pYuandingTopicNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingTopicNumIn(List<Integer> values) {
            addCriterion("p_yuanding_topic_num in", values, "pYuandingTopicNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingTopicNumNotIn(List<Integer> values) {
            addCriterion("p_yuanding_topic_num not in", values, "pYuandingTopicNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingTopicNumBetween(Integer value1, Integer value2) {
            addCriterion("p_yuanding_topic_num between", value1, value2, "pYuandingTopicNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingTopicNumNotBetween(Integer value1, Integer value2) {
            addCriterion("p_yuanding_topic_num not between", value1, value2, "pYuandingTopicNum");
            return (Criteria) this;
        }

        public Criteria andPYuandingRegistIpIsNull() {
            addCriterion("p_yuanding_regist_ip is null");
            return (Criteria) this;
        }

        public Criteria andPYuandingRegistIpIsNotNull() {
            addCriterion("p_yuanding_regist_ip is not null");
            return (Criteria) this;
        }

        public Criteria andPYuandingRegistIpEqualTo(String value) {
            addCriterion("p_yuanding_regist_ip =", value, "pYuandingRegistIp");
            return (Criteria) this;
        }

        public Criteria andPYuandingRegistIpNotEqualTo(String value) {
            addCriterion("p_yuanding_regist_ip <>", value, "pYuandingRegistIp");
            return (Criteria) this;
        }

        public Criteria andPYuandingRegistIpGreaterThan(String value) {
            addCriterion("p_yuanding_regist_ip >", value, "pYuandingRegistIp");
            return (Criteria) this;
        }

        public Criteria andPYuandingRegistIpGreaterThanOrEqualTo(String value) {
            addCriterion("p_yuanding_regist_ip >=", value, "pYuandingRegistIp");
            return (Criteria) this;
        }

        public Criteria andPYuandingRegistIpLessThan(String value) {
            addCriterion("p_yuanding_regist_ip <", value, "pYuandingRegistIp");
            return (Criteria) this;
        }

        public Criteria andPYuandingRegistIpLessThanOrEqualTo(String value) {
            addCriterion("p_yuanding_regist_ip <=", value, "pYuandingRegistIp");
            return (Criteria) this;
        }

        public Criteria andPYuandingRegistIpLike(String value) {
            addCriterion("p_yuanding_regist_ip like", value, "pYuandingRegistIp");
            return (Criteria) this;
        }

        public Criteria andPYuandingRegistIpNotLike(String value) {
            addCriterion("p_yuanding_regist_ip not like", value, "pYuandingRegistIp");
            return (Criteria) this;
        }

        public Criteria andPYuandingRegistIpIn(List<String> values) {
            addCriterion("p_yuanding_regist_ip in", values, "pYuandingRegistIp");
            return (Criteria) this;
        }

        public Criteria andPYuandingRegistIpNotIn(List<String> values) {
            addCriterion("p_yuanding_regist_ip not in", values, "pYuandingRegistIp");
            return (Criteria) this;
        }

        public Criteria andPYuandingRegistIpBetween(String value1, String value2) {
            addCriterion("p_yuanding_regist_ip between", value1, value2, "pYuandingRegistIp");
            return (Criteria) this;
        }

        public Criteria andPYuandingRegistIpNotBetween(String value1, String value2) {
            addCriterion("p_yuanding_regist_ip not between", value1, value2, "pYuandingRegistIp");
            return (Criteria) this;
        }

        public Criteria andPYuandingRegistTimeIsNull() {
            addCriterion("p_yuanding_regist_time is null");
            return (Criteria) this;
        }

        public Criteria andPYuandingRegistTimeIsNotNull() {
            addCriterion("p_yuanding_regist_time is not null");
            return (Criteria) this;
        }

        public Criteria andPYuandingRegistTimeEqualTo(Date value) {
            addCriterion("p_yuanding_regist_time =", value, "pYuandingRegistTime");
            return (Criteria) this;
        }

        public Criteria andPYuandingRegistTimeNotEqualTo(Date value) {
            addCriterion("p_yuanding_regist_time <>", value, "pYuandingRegistTime");
            return (Criteria) this;
        }

        public Criteria andPYuandingRegistTimeGreaterThan(Date value) {
            addCriterion("p_yuanding_regist_time >", value, "pYuandingRegistTime");
            return (Criteria) this;
        }

        public Criteria andPYuandingRegistTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("p_yuanding_regist_time >=", value, "pYuandingRegistTime");
            return (Criteria) this;
        }

        public Criteria andPYuandingRegistTimeLessThan(Date value) {
            addCriterion("p_yuanding_regist_time <", value, "pYuandingRegistTime");
            return (Criteria) this;
        }

        public Criteria andPYuandingRegistTimeLessThanOrEqualTo(Date value) {
            addCriterion("p_yuanding_regist_time <=", value, "pYuandingRegistTime");
            return (Criteria) this;
        }

        public Criteria andPYuandingRegistTimeIn(List<Date> values) {
            addCriterion("p_yuanding_regist_time in", values, "pYuandingRegistTime");
            return (Criteria) this;
        }

        public Criteria andPYuandingRegistTimeNotIn(List<Date> values) {
            addCriterion("p_yuanding_regist_time not in", values, "pYuandingRegistTime");
            return (Criteria) this;
        }

        public Criteria andPYuandingRegistTimeBetween(Date value1, Date value2) {
            addCriterion("p_yuanding_regist_time between", value1, value2, "pYuandingRegistTime");
            return (Criteria) this;
        }

        public Criteria andPYuandingRegistTimeNotBetween(Date value1, Date value2) {
            addCriterion("p_yuanding_regist_time not between", value1, value2, "pYuandingRegistTime");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastIpIsNull() {
            addCriterion("p_yuanding_login_last_ip is null");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastIpIsNotNull() {
            addCriterion("p_yuanding_login_last_ip is not null");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastIpEqualTo(String value) {
            addCriterion("p_yuanding_login_last_ip =", value, "pYuandingLoginLastIp");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastIpNotEqualTo(String value) {
            addCriterion("p_yuanding_login_last_ip <>", value, "pYuandingLoginLastIp");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastIpGreaterThan(String value) {
            addCriterion("p_yuanding_login_last_ip >", value, "pYuandingLoginLastIp");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastIpGreaterThanOrEqualTo(String value) {
            addCriterion("p_yuanding_login_last_ip >=", value, "pYuandingLoginLastIp");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastIpLessThan(String value) {
            addCriterion("p_yuanding_login_last_ip <", value, "pYuandingLoginLastIp");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastIpLessThanOrEqualTo(String value) {
            addCriterion("p_yuanding_login_last_ip <=", value, "pYuandingLoginLastIp");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastIpLike(String value) {
            addCriterion("p_yuanding_login_last_ip like", value, "pYuandingLoginLastIp");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastIpNotLike(String value) {
            addCriterion("p_yuanding_login_last_ip not like", value, "pYuandingLoginLastIp");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastIpIn(List<String> values) {
            addCriterion("p_yuanding_login_last_ip in", values, "pYuandingLoginLastIp");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastIpNotIn(List<String> values) {
            addCriterion("p_yuanding_login_last_ip not in", values, "pYuandingLoginLastIp");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastIpBetween(String value1, String value2) {
            addCriterion("p_yuanding_login_last_ip between", value1, value2, "pYuandingLoginLastIp");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastIpNotBetween(String value1, String value2) {
            addCriterion("p_yuanding_login_last_ip not between", value1, value2, "pYuandingLoginLastIp");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastAddressIsNull() {
            addCriterion("p_yuanding_login_last_address is null");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastAddressIsNotNull() {
            addCriterion("p_yuanding_login_last_address is not null");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastAddressEqualTo(String value) {
            addCriterion("p_yuanding_login_last_address =", value, "pYuandingLoginLastAddress");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastAddressNotEqualTo(String value) {
            addCriterion("p_yuanding_login_last_address <>", value, "pYuandingLoginLastAddress");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastAddressGreaterThan(String value) {
            addCriterion("p_yuanding_login_last_address >", value, "pYuandingLoginLastAddress");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastAddressGreaterThanOrEqualTo(String value) {
            addCriterion("p_yuanding_login_last_address >=", value, "pYuandingLoginLastAddress");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastAddressLessThan(String value) {
            addCriterion("p_yuanding_login_last_address <", value, "pYuandingLoginLastAddress");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastAddressLessThanOrEqualTo(String value) {
            addCriterion("p_yuanding_login_last_address <=", value, "pYuandingLoginLastAddress");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastAddressLike(String value) {
            addCriterion("p_yuanding_login_last_address like", value, "pYuandingLoginLastAddress");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastAddressNotLike(String value) {
            addCriterion("p_yuanding_login_last_address not like", value, "pYuandingLoginLastAddress");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastAddressIn(List<String> values) {
            addCriterion("p_yuanding_login_last_address in", values, "pYuandingLoginLastAddress");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastAddressNotIn(List<String> values) {
            addCriterion("p_yuanding_login_last_address not in", values, "pYuandingLoginLastAddress");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastAddressBetween(String value1, String value2) {
            addCriterion("p_yuanding_login_last_address between", value1, value2, "pYuandingLoginLastAddress");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastAddressNotBetween(String value1, String value2) {
            addCriterion("p_yuanding_login_last_address not between", value1, value2, "pYuandingLoginLastAddress");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastTimeIsNull() {
            addCriterion("p_yuanding_login_last_time is null");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastTimeIsNotNull() {
            addCriterion("p_yuanding_login_last_time is not null");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastTimeEqualTo(Date value) {
            addCriterion("p_yuanding_login_last_time =", value, "pYuandingLoginLastTime");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastTimeNotEqualTo(Date value) {
            addCriterion("p_yuanding_login_last_time <>", value, "pYuandingLoginLastTime");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastTimeGreaterThan(Date value) {
            addCriterion("p_yuanding_login_last_time >", value, "pYuandingLoginLastTime");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("p_yuanding_login_last_time >=", value, "pYuandingLoginLastTime");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastTimeLessThan(Date value) {
            addCriterion("p_yuanding_login_last_time <", value, "pYuandingLoginLastTime");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastTimeLessThanOrEqualTo(Date value) {
            addCriterion("p_yuanding_login_last_time <=", value, "pYuandingLoginLastTime");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastTimeIn(List<Date> values) {
            addCriterion("p_yuanding_login_last_time in", values, "pYuandingLoginLastTime");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastTimeNotIn(List<Date> values) {
            addCriterion("p_yuanding_login_last_time not in", values, "pYuandingLoginLastTime");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastTimeBetween(Date value1, Date value2) {
            addCriterion("p_yuanding_login_last_time between", value1, value2, "pYuandingLoginLastTime");
            return (Criteria) this;
        }

        public Criteria andPYuandingLoginLastTimeNotBetween(Date value1, Date value2) {
            addCriterion("p_yuanding_login_last_time not between", value1, value2, "pYuandingLoginLastTime");
            return (Criteria) this;
        }

        public Criteria andPAddressInfoIsNull() {
            addCriterion("p_address_info is null");
            return (Criteria) this;
        }

        public Criteria andPAddressInfoIsNotNull() {
            addCriterion("p_address_info is not null");
            return (Criteria) this;
        }

        public Criteria andPAddressInfoEqualTo(String value) {
            addCriterion("p_address_info =", value, "pAddressInfo");
            return (Criteria) this;
        }

        public Criteria andPAddressInfoNotEqualTo(String value) {
            addCriterion("p_address_info <>", value, "pAddressInfo");
            return (Criteria) this;
        }

        public Criteria andPAddressInfoGreaterThan(String value) {
            addCriterion("p_address_info >", value, "pAddressInfo");
            return (Criteria) this;
        }

        public Criteria andPAddressInfoGreaterThanOrEqualTo(String value) {
            addCriterion("p_address_info >=", value, "pAddressInfo");
            return (Criteria) this;
        }

        public Criteria andPAddressInfoLessThan(String value) {
            addCriterion("p_address_info <", value, "pAddressInfo");
            return (Criteria) this;
        }

        public Criteria andPAddressInfoLessThanOrEqualTo(String value) {
            addCriterion("p_address_info <=", value, "pAddressInfo");
            return (Criteria) this;
        }

        public Criteria andPAddressInfoLike(String value) {
            addCriterion("p_address_info like", value, "pAddressInfo");
            return (Criteria) this;
        }

        public Criteria andPAddressInfoNotLike(String value) {
            addCriterion("p_address_info not like", value, "pAddressInfo");
            return (Criteria) this;
        }

        public Criteria andPAddressInfoIn(List<String> values) {
            addCriterion("p_address_info in", values, "pAddressInfo");
            return (Criteria) this;
        }

        public Criteria andPAddressInfoNotIn(List<String> values) {
            addCriterion("p_address_info not in", values, "pAddressInfo");
            return (Criteria) this;
        }

        public Criteria andPAddressInfoBetween(String value1, String value2) {
            addCriterion("p_address_info between", value1, value2, "pAddressInfo");
            return (Criteria) this;
        }

        public Criteria andPAddressInfoNotBetween(String value1, String value2) {
            addCriterion("p_address_info not between", value1, value2, "pAddressInfo");
            return (Criteria) this;
        }

        public Criteria andPTrajectoryInfoIsNull() {
            addCriterion("p_trajectory_info is null");
            return (Criteria) this;
        }

        public Criteria andPTrajectoryInfoIsNotNull() {
            addCriterion("p_trajectory_info is not null");
            return (Criteria) this;
        }

        public Criteria andPTrajectoryInfoEqualTo(String value) {
            addCriterion("p_trajectory_info =", value, "pTrajectoryInfo");
            return (Criteria) this;
        }

        public Criteria andPTrajectoryInfoNotEqualTo(String value) {
            addCriterion("p_trajectory_info <>", value, "pTrajectoryInfo");
            return (Criteria) this;
        }

        public Criteria andPTrajectoryInfoGreaterThan(String value) {
            addCriterion("p_trajectory_info >", value, "pTrajectoryInfo");
            return (Criteria) this;
        }

        public Criteria andPTrajectoryInfoGreaterThanOrEqualTo(String value) {
            addCriterion("p_trajectory_info >=", value, "pTrajectoryInfo");
            return (Criteria) this;
        }

        public Criteria andPTrajectoryInfoLessThan(String value) {
            addCriterion("p_trajectory_info <", value, "pTrajectoryInfo");
            return (Criteria) this;
        }

        public Criteria andPTrajectoryInfoLessThanOrEqualTo(String value) {
            addCriterion("p_trajectory_info <=", value, "pTrajectoryInfo");
            return (Criteria) this;
        }

        public Criteria andPTrajectoryInfoLike(String value) {
            addCriterion("p_trajectory_info like", value, "pTrajectoryInfo");
            return (Criteria) this;
        }

        public Criteria andPTrajectoryInfoNotLike(String value) {
            addCriterion("p_trajectory_info not like", value, "pTrajectoryInfo");
            return (Criteria) this;
        }

        public Criteria andPTrajectoryInfoIn(List<String> values) {
            addCriterion("p_trajectory_info in", values, "pTrajectoryInfo");
            return (Criteria) this;
        }

        public Criteria andPTrajectoryInfoNotIn(List<String> values) {
            addCriterion("p_trajectory_info not in", values, "pTrajectoryInfo");
            return (Criteria) this;
        }

        public Criteria andPTrajectoryInfoBetween(String value1, String value2) {
            addCriterion("p_trajectory_info between", value1, value2, "pTrajectoryInfo");
            return (Criteria) this;
        }

        public Criteria andPTrajectoryInfoNotBetween(String value1, String value2) {
            addCriterion("p_trajectory_info not between", value1, value2, "pTrajectoryInfo");
            return (Criteria) this;
        }

        public Criteria andPEvidenceIsNull() {
            addCriterion("p_evidence is null");
            return (Criteria) this;
        }

        public Criteria andPEvidenceIsNotNull() {
            addCriterion("p_evidence is not null");
            return (Criteria) this;
        }

        public Criteria andPEvidenceEqualTo(String value) {
            addCriterion("p_evidence =", value, "pEvidence");
            return (Criteria) this;
        }

        public Criteria andPEvidenceNotEqualTo(String value) {
            addCriterion("p_evidence <>", value, "pEvidence");
            return (Criteria) this;
        }

        public Criteria andPEvidenceGreaterThan(String value) {
            addCriterion("p_evidence >", value, "pEvidence");
            return (Criteria) this;
        }

        public Criteria andPEvidenceGreaterThanOrEqualTo(String value) {
            addCriterion("p_evidence >=", value, "pEvidence");
            return (Criteria) this;
        }

        public Criteria andPEvidenceLessThan(String value) {
            addCriterion("p_evidence <", value, "pEvidence");
            return (Criteria) this;
        }

        public Criteria andPEvidenceLessThanOrEqualTo(String value) {
            addCriterion("p_evidence <=", value, "pEvidence");
            return (Criteria) this;
        }

        public Criteria andPEvidenceLike(String value) {
            addCriterion("p_evidence like", value, "pEvidence");
            return (Criteria) this;
        }

        public Criteria andPEvidenceNotLike(String value) {
            addCriterion("p_evidence not like", value, "pEvidence");
            return (Criteria) this;
        }

        public Criteria andPEvidenceIn(List<String> values) {
            addCriterion("p_evidence in", values, "pEvidence");
            return (Criteria) this;
        }

        public Criteria andPEvidenceNotIn(List<String> values) {
            addCriterion("p_evidence not in", values, "pEvidence");
            return (Criteria) this;
        }

        public Criteria andPEvidenceBetween(String value1, String value2) {
            addCriterion("p_evidence between", value1, value2, "pEvidence");
            return (Criteria) this;
        }

        public Criteria andPEvidenceNotBetween(String value1, String value2) {
            addCriterion("p_evidence not between", value1, value2, "pEvidence");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table person_record
     *
     * @mbggenerated do_not_delete_during_merge Fri Oct 26 17:48:36 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}