package com.judge.demo.Entity;

import java.io.Serializable;
import java.util.Date;

public class Record implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private Long recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_sender_zhifubao_account
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordSenderZhifubaoAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_sender_zhifubao_account_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordSenderZhifubaoAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_sender_phone
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordSenderPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_sender_name
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordSenderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_sender_identity_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordSenderIdentityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_sender_last_login_city
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordSenderLastLoginCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_sender_often_login_city
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordSenderOftenLoginCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_sender_taobao_account
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordSenderTaobaoAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_sender_taobao_account_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordSenderTaobaoAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_receiver_zhifubao_account
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordReceiverZhifubaoAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_receiver_zhifubao_account_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordReceiverZhifubaoAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_receiver_phone
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordReceiverPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_receiver_name
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordReceiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_receiver_identity_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordReceiverIdentityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_receiver_last_login_city
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordReceiverLastLoginCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_receiver_often_login_city
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordReceiverOftenLoginCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_receiver_taobao_account
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordReceiverTaobaoAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_receiver_taobao_account_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordReceiverTaobaoAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_gmt_create
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private Date recordGmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_transfer_title
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordTransferTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_suspicion_transfer_title
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordSuspicionTransferTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_transfer_fee
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private Double recordTransferFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_feather
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordFeather;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_collection_company
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordCollectionCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_receiver_account
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordReceiverAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_sender_gmt_last_visit
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private Date recordSenderGmtLastVisit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.reocrd_receiver_gmt_last_visit
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private Date reocrdReceiverGmtLastVisit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_sender_default_address
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordSenderDefaultAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_sender_latest_address
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordSenderLatestAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_sender_latest_phone
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordSenderLatestPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_sender_latest_receiver
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordSenderLatestReceiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_receiver_default_address
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordReceiverDefaultAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_receiver_latest_address
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordReceiverLatestAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_receiver_latest_phone
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordReceiverLatestPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_receiver_latest_receiver
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordReceiverLatestReceiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_all
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private String recordAll;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table record
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_id
     *
     * @return the value of record.record_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public Long getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_id
     *
     * @param recordId the value for record.record_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordId(Long recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_sender_zhifubao_account
     *
     * @return the value of record.record_sender_zhifubao_account
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordSenderZhifubaoAccount() {
        return recordSenderZhifubaoAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_sender_zhifubao_account
     *
     * @param recordSenderZhifubaoAccount the value for record.record_sender_zhifubao_account
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordSenderZhifubaoAccount(String recordSenderZhifubaoAccount) {
        this.recordSenderZhifubaoAccount = recordSenderZhifubaoAccount == null ? null : recordSenderZhifubaoAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_sender_zhifubao_account_id
     *
     * @return the value of record.record_sender_zhifubao_account_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordSenderZhifubaoAccountId() {
        return recordSenderZhifubaoAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_sender_zhifubao_account_id
     *
     * @param recordSenderZhifubaoAccountId the value for record.record_sender_zhifubao_account_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordSenderZhifubaoAccountId(String recordSenderZhifubaoAccountId) {
        this.recordSenderZhifubaoAccountId = recordSenderZhifubaoAccountId == null ? null : recordSenderZhifubaoAccountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_sender_phone
     *
     * @return the value of record.record_sender_phone
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordSenderPhone() {
        return recordSenderPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_sender_phone
     *
     * @param recordSenderPhone the value for record.record_sender_phone
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordSenderPhone(String recordSenderPhone) {
        this.recordSenderPhone = recordSenderPhone == null ? null : recordSenderPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_sender_name
     *
     * @return the value of record.record_sender_name
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordSenderName() {
        return recordSenderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_sender_name
     *
     * @param recordSenderName the value for record.record_sender_name
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordSenderName(String recordSenderName) {
        this.recordSenderName = recordSenderName == null ? null : recordSenderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_sender_identity_id
     *
     * @return the value of record.record_sender_identity_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordSenderIdentityId() {
        return recordSenderIdentityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_sender_identity_id
     *
     * @param recordSenderIdentityId the value for record.record_sender_identity_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordSenderIdentityId(String recordSenderIdentityId) {
        this.recordSenderIdentityId = recordSenderIdentityId == null ? null : recordSenderIdentityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_sender_last_login_city
     *
     * @return the value of record.record_sender_last_login_city
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordSenderLastLoginCity() {
        return recordSenderLastLoginCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_sender_last_login_city
     *
     * @param recordSenderLastLoginCity the value for record.record_sender_last_login_city
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordSenderLastLoginCity(String recordSenderLastLoginCity) {
        this.recordSenderLastLoginCity = recordSenderLastLoginCity == null ? null : recordSenderLastLoginCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_sender_often_login_city
     *
     * @return the value of record.record_sender_often_login_city
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordSenderOftenLoginCity() {
        return recordSenderOftenLoginCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_sender_often_login_city
     *
     * @param recordSenderOftenLoginCity the value for record.record_sender_often_login_city
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordSenderOftenLoginCity(String recordSenderOftenLoginCity) {
        this.recordSenderOftenLoginCity = recordSenderOftenLoginCity == null ? null : recordSenderOftenLoginCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_sender_taobao_account
     *
     * @return the value of record.record_sender_taobao_account
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordSenderTaobaoAccount() {
        return recordSenderTaobaoAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_sender_taobao_account
     *
     * @param recordSenderTaobaoAccount the value for record.record_sender_taobao_account
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordSenderTaobaoAccount(String recordSenderTaobaoAccount) {
        this.recordSenderTaobaoAccount = recordSenderTaobaoAccount == null ? null : recordSenderTaobaoAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_sender_taobao_account_id
     *
     * @return the value of record.record_sender_taobao_account_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordSenderTaobaoAccountId() {
        return recordSenderTaobaoAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_sender_taobao_account_id
     *
     * @param recordSenderTaobaoAccountId the value for record.record_sender_taobao_account_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordSenderTaobaoAccountId(String recordSenderTaobaoAccountId) {
        this.recordSenderTaobaoAccountId = recordSenderTaobaoAccountId == null ? null : recordSenderTaobaoAccountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_receiver_zhifubao_account
     *
     * @return the value of record.record_receiver_zhifubao_account
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordReceiverZhifubaoAccount() {
        return recordReceiverZhifubaoAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_receiver_zhifubao_account
     *
     * @param recordReceiverZhifubaoAccount the value for record.record_receiver_zhifubao_account
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordReceiverZhifubaoAccount(String recordReceiverZhifubaoAccount) {
        this.recordReceiverZhifubaoAccount = recordReceiverZhifubaoAccount == null ? null : recordReceiverZhifubaoAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_receiver_zhifubao_account_id
     *
     * @return the value of record.record_receiver_zhifubao_account_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordReceiverZhifubaoAccountId() {
        return recordReceiverZhifubaoAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_receiver_zhifubao_account_id
     *
     * @param recordReceiverZhifubaoAccountId the value for record.record_receiver_zhifubao_account_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordReceiverZhifubaoAccountId(String recordReceiverZhifubaoAccountId) {
        this.recordReceiverZhifubaoAccountId = recordReceiverZhifubaoAccountId == null ? null : recordReceiverZhifubaoAccountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_receiver_phone
     *
     * @return the value of record.record_receiver_phone
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordReceiverPhone() {
        return recordReceiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_receiver_phone
     *
     * @param recordReceiverPhone the value for record.record_receiver_phone
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordReceiverPhone(String recordReceiverPhone) {
        this.recordReceiverPhone = recordReceiverPhone == null ? null : recordReceiverPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_receiver_name
     *
     * @return the value of record.record_receiver_name
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordReceiverName() {
        return recordReceiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_receiver_name
     *
     * @param recordReceiverName the value for record.record_receiver_name
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordReceiverName(String recordReceiverName) {
        this.recordReceiverName = recordReceiverName == null ? null : recordReceiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_receiver_identity_id
     *
     * @return the value of record.record_receiver_identity_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordReceiverIdentityId() {
        return recordReceiverIdentityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_receiver_identity_id
     *
     * @param recordReceiverIdentityId the value for record.record_receiver_identity_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordReceiverIdentityId(String recordReceiverIdentityId) {
        this.recordReceiverIdentityId = recordReceiverIdentityId == null ? null : recordReceiverIdentityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_receiver_last_login_city
     *
     * @return the value of record.record_receiver_last_login_city
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordReceiverLastLoginCity() {
        return recordReceiverLastLoginCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_receiver_last_login_city
     *
     * @param recordReceiverLastLoginCity the value for record.record_receiver_last_login_city
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordReceiverLastLoginCity(String recordReceiverLastLoginCity) {
        this.recordReceiverLastLoginCity = recordReceiverLastLoginCity == null ? null : recordReceiverLastLoginCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_receiver_often_login_city
     *
     * @return the value of record.record_receiver_often_login_city
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordReceiverOftenLoginCity() {
        return recordReceiverOftenLoginCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_receiver_often_login_city
     *
     * @param recordReceiverOftenLoginCity the value for record.record_receiver_often_login_city
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordReceiverOftenLoginCity(String recordReceiverOftenLoginCity) {
        this.recordReceiverOftenLoginCity = recordReceiverOftenLoginCity == null ? null : recordReceiverOftenLoginCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_receiver_taobao_account
     *
     * @return the value of record.record_receiver_taobao_account
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordReceiverTaobaoAccount() {
        return recordReceiverTaobaoAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_receiver_taobao_account
     *
     * @param recordReceiverTaobaoAccount the value for record.record_receiver_taobao_account
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordReceiverTaobaoAccount(String recordReceiverTaobaoAccount) {
        this.recordReceiverTaobaoAccount = recordReceiverTaobaoAccount == null ? null : recordReceiverTaobaoAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_receiver_taobao_account_id
     *
     * @return the value of record.record_receiver_taobao_account_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordReceiverTaobaoAccountId() {
        return recordReceiverTaobaoAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_receiver_taobao_account_id
     *
     * @param recordReceiverTaobaoAccountId the value for record.record_receiver_taobao_account_id
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordReceiverTaobaoAccountId(String recordReceiverTaobaoAccountId) {
        this.recordReceiverTaobaoAccountId = recordReceiverTaobaoAccountId == null ? null : recordReceiverTaobaoAccountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_gmt_create
     *
     * @return the value of record.record_gmt_create
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public Date getRecordGmtCreate() {
        return recordGmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_gmt_create
     *
     * @param recordGmtCreate the value for record.record_gmt_create
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordGmtCreate(Date recordGmtCreate) {
        this.recordGmtCreate = recordGmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_transfer_title
     *
     * @return the value of record.record_transfer_title
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordTransferTitle() {
        return recordTransferTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_transfer_title
     *
     * @param recordTransferTitle the value for record.record_transfer_title
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordTransferTitle(String recordTransferTitle) {
        this.recordTransferTitle = recordTransferTitle == null ? null : recordTransferTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_suspicion_transfer_title
     *
     * @return the value of record.record_suspicion_transfer_title
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordSuspicionTransferTitle() {
        return recordSuspicionTransferTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_suspicion_transfer_title
     *
     * @param recordSuspicionTransferTitle the value for record.record_suspicion_transfer_title
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordSuspicionTransferTitle(String recordSuspicionTransferTitle) {
        this.recordSuspicionTransferTitle = recordSuspicionTransferTitle == null ? null : recordSuspicionTransferTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_transfer_fee
     *
     * @return the value of record.record_transfer_fee
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public Double getRecordTransferFee() {
        return recordTransferFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_transfer_fee
     *
     * @param recordTransferFee the value for record.record_transfer_fee
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordTransferFee(Double recordTransferFee) {
        this.recordTransferFee = recordTransferFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_feather
     *
     * @return the value of record.record_feather
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordFeather() {
        return recordFeather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_feather
     *
     * @param recordFeather the value for record.record_feather
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordFeather(String recordFeather) {
        this.recordFeather = recordFeather == null ? null : recordFeather.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_collection_company
     *
     * @return the value of record.record_collection_company
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordCollectionCompany() {
        return recordCollectionCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_collection_company
     *
     * @param recordCollectionCompany the value for record.record_collection_company
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordCollectionCompany(String recordCollectionCompany) {
        this.recordCollectionCompany = recordCollectionCompany == null ? null : recordCollectionCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_receiver_account
     *
     * @return the value of record.record_receiver_account
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordReceiverAccount() {
        return recordReceiverAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_receiver_account
     *
     * @param recordReceiverAccount the value for record.record_receiver_account
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordReceiverAccount(String recordReceiverAccount) {
        this.recordReceiverAccount = recordReceiverAccount == null ? null : recordReceiverAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_sender_gmt_last_visit
     *
     * @return the value of record.record_sender_gmt_last_visit
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public Date getRecordSenderGmtLastVisit() {
        return recordSenderGmtLastVisit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_sender_gmt_last_visit
     *
     * @param recordSenderGmtLastVisit the value for record.record_sender_gmt_last_visit
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordSenderGmtLastVisit(Date recordSenderGmtLastVisit) {
        this.recordSenderGmtLastVisit = recordSenderGmtLastVisit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.reocrd_receiver_gmt_last_visit
     *
     * @return the value of record.reocrd_receiver_gmt_last_visit
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public Date getReocrdReceiverGmtLastVisit() {
        return reocrdReceiverGmtLastVisit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.reocrd_receiver_gmt_last_visit
     *
     * @param reocrdReceiverGmtLastVisit the value for record.reocrd_receiver_gmt_last_visit
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setReocrdReceiverGmtLastVisit(Date reocrdReceiverGmtLastVisit) {
        this.reocrdReceiverGmtLastVisit = reocrdReceiverGmtLastVisit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_sender_default_address
     *
     * @return the value of record.record_sender_default_address
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordSenderDefaultAddress() {
        return recordSenderDefaultAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_sender_default_address
     *
     * @param recordSenderDefaultAddress the value for record.record_sender_default_address
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordSenderDefaultAddress(String recordSenderDefaultAddress) {
        this.recordSenderDefaultAddress = recordSenderDefaultAddress == null ? null : recordSenderDefaultAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_sender_latest_address
     *
     * @return the value of record.record_sender_latest_address
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordSenderLatestAddress() {
        return recordSenderLatestAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_sender_latest_address
     *
     * @param recordSenderLatestAddress the value for record.record_sender_latest_address
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordSenderLatestAddress(String recordSenderLatestAddress) {
        this.recordSenderLatestAddress = recordSenderLatestAddress == null ? null : recordSenderLatestAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_sender_latest_phone
     *
     * @return the value of record.record_sender_latest_phone
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordSenderLatestPhone() {
        return recordSenderLatestPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_sender_latest_phone
     *
     * @param recordSenderLatestPhone the value for record.record_sender_latest_phone
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordSenderLatestPhone(String recordSenderLatestPhone) {
        this.recordSenderLatestPhone = recordSenderLatestPhone == null ? null : recordSenderLatestPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_sender_latest_receiver
     *
     * @return the value of record.record_sender_latest_receiver
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordSenderLatestReceiver() {
        return recordSenderLatestReceiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_sender_latest_receiver
     *
     * @param recordSenderLatestReceiver the value for record.record_sender_latest_receiver
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordSenderLatestReceiver(String recordSenderLatestReceiver) {
        this.recordSenderLatestReceiver = recordSenderLatestReceiver == null ? null : recordSenderLatestReceiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_receiver_default_address
     *
     * @return the value of record.record_receiver_default_address
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordReceiverDefaultAddress() {
        return recordReceiverDefaultAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_receiver_default_address
     *
     * @param recordReceiverDefaultAddress the value for record.record_receiver_default_address
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordReceiverDefaultAddress(String recordReceiverDefaultAddress) {
        this.recordReceiverDefaultAddress = recordReceiverDefaultAddress == null ? null : recordReceiverDefaultAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_receiver_latest_address
     *
     * @return the value of record.record_receiver_latest_address
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordReceiverLatestAddress() {
        return recordReceiverLatestAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_receiver_latest_address
     *
     * @param recordReceiverLatestAddress the value for record.record_receiver_latest_address
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordReceiverLatestAddress(String recordReceiverLatestAddress) {
        this.recordReceiverLatestAddress = recordReceiverLatestAddress == null ? null : recordReceiverLatestAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_receiver_latest_phone
     *
     * @return the value of record.record_receiver_latest_phone
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordReceiverLatestPhone() {
        return recordReceiverLatestPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_receiver_latest_phone
     *
     * @param recordReceiverLatestPhone the value for record.record_receiver_latest_phone
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordReceiverLatestPhone(String recordReceiverLatestPhone) {
        this.recordReceiverLatestPhone = recordReceiverLatestPhone == null ? null : recordReceiverLatestPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_receiver_latest_receiver
     *
     * @return the value of record.record_receiver_latest_receiver
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordReceiverLatestReceiver() {
        return recordReceiverLatestReceiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_receiver_latest_receiver
     *
     * @param recordReceiverLatestReceiver the value for record.record_receiver_latest_receiver
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordReceiverLatestReceiver(String recordReceiverLatestReceiver) {
        this.recordReceiverLatestReceiver = recordReceiverLatestReceiver == null ? null : recordReceiverLatestReceiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_all
     *
     * @return the value of record.record_all
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public String getRecordAll() {
        return recordAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_all
     *
     * @param recordAll the value for record.record_all
     *
     * @mbggenerated Sat Oct 20 23:01:30 CST 2018
     */
    public void setRecordAll(String recordAll) {
        this.recordAll = recordAll == null ? null : recordAll.trim();
    }
}