package com.judge.demo.Entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import java.util.Map;

public class TransferRecord implements Serializable {
    public static String transfer_query="#";
    public static Date transfer_beginDate=new Date();
    public static Date transfer_endDate=new Date();
    public static Map<String,Double> transfer_InOut;
    public static List<TransferRecord> transfer_list;
    public static int transfer_flag=1;
    public static int count = 0;
    public static int all_count=0;
    public static int all_transfer_flag=1;
    public static Map<String,Double> all_transfer_InOut;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.transfer_record_id
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private Long transferRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.transfer_record_flow_id
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private String transferRecordFlowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.transfer_record_create_time
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private Date transferRecordCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.transfer_record_pay_time
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private Date transferRecordPayTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.transfer_record_pay_fee
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private Double transferRecordPayFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.transfer_record_pay_zhifubao
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private String transferRecordPayZhifubao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.transfer_record_pay_zhifubao_id
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private String transferRecordPayZhifubaoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.transfer_record_pay_name
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private String transferRecordPayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.transfer_record_collection_zhifubao
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private String transferRecordCollectionZhifubao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.transfer_record_collection_zhifubao_id
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private String transferRecordCollectionZhifubaoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.transfer_record_collection_name
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private String transferRecordCollectionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.transfer_record_remark
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private String transferRecordRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.transfer_record_flow
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private String transferRecordFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.transfer_record_status
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private String transferRecordStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.transfer_record_product_name
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private String transferRecordProductName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.transfer_record_index
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private String transferRecordIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transfer_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.transfer_record_id
     *
     * @return the value of transfer_record.transfer_record_id
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public Long getTransferRecordId() {
        return transferRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.transfer_record_id
     *
     * @param transferRecordId the value for transfer_record.transfer_record_id
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setTransferRecordId(Long transferRecordId) {
        this.transferRecordId = transferRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.transfer_record_flow_id
     *
     * @return the value of transfer_record.transfer_record_flow_id
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public String getTransferRecordFlowId() {
        return transferRecordFlowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.transfer_record_flow_id
     *
     * @param transferRecordFlowId the value for transfer_record.transfer_record_flow_id
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setTransferRecordFlowId(String transferRecordFlowId) {
        this.transferRecordFlowId = transferRecordFlowId == null ? null : transferRecordFlowId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.transfer_record_create_time
     *
     * @return the value of transfer_record.transfer_record_create_time
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public Date getTransferRecordCreateTime() {
        return transferRecordCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.transfer_record_create_time
     *
     * @param transferRecordCreateTime the value for transfer_record.transfer_record_create_time
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setTransferRecordCreateTime(Date transferRecordCreateTime) {
        this.transferRecordCreateTime = transferRecordCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.transfer_record_pay_time
     *
     * @return the value of transfer_record.transfer_record_pay_time
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public Date getTransferRecordPayTime() {
        return transferRecordPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.transfer_record_pay_time
     *
     * @param transferRecordPayTime the value for transfer_record.transfer_record_pay_time
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setTransferRecordPayTime(Date transferRecordPayTime) {
        this.transferRecordPayTime = transferRecordPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.transfer_record_pay_fee
     *
     * @return the value of transfer_record.transfer_record_pay_fee
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public Double getTransferRecordPayFee() {
        return transferRecordPayFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.transfer_record_pay_fee
     *
     * @param transferRecordPayFee the value for transfer_record.transfer_record_pay_fee
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setTransferRecordPayFee(Double transferRecordPayFee) {
        this.transferRecordPayFee = transferRecordPayFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.transfer_record_pay_zhifubao
     *
     * @return the value of transfer_record.transfer_record_pay_zhifubao
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public String getTransferRecordPayZhifubao() {
        return transferRecordPayZhifubao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.transfer_record_pay_zhifubao
     *
     * @param transferRecordPayZhifubao the value for transfer_record.transfer_record_pay_zhifubao
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setTransferRecordPayZhifubao(String transferRecordPayZhifubao) {
        this.transferRecordPayZhifubao = transferRecordPayZhifubao == null ? null : transferRecordPayZhifubao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.transfer_record_pay_zhifubao_id
     *
     * @return the value of transfer_record.transfer_record_pay_zhifubao_id
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public String getTransferRecordPayZhifubaoId() {
        return transferRecordPayZhifubaoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.transfer_record_pay_zhifubao_id
     *
     * @param transferRecordPayZhifubaoId the value for transfer_record.transfer_record_pay_zhifubao_id
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setTransferRecordPayZhifubaoId(String transferRecordPayZhifubaoId) {
        this.transferRecordPayZhifubaoId = transferRecordPayZhifubaoId == null ? null : transferRecordPayZhifubaoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.transfer_record_pay_name
     *
     * @return the value of transfer_record.transfer_record_pay_name
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public String getTransferRecordPayName() {
        return transferRecordPayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.transfer_record_pay_name
     *
     * @param transferRecordPayName the value for transfer_record.transfer_record_pay_name
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setTransferRecordPayName(String transferRecordPayName) {
        this.transferRecordPayName = transferRecordPayName == null ? null : transferRecordPayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.transfer_record_collection_zhifubao
     *
     * @return the value of transfer_record.transfer_record_collection_zhifubao
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public String getTransferRecordCollectionZhifubao() {
        return transferRecordCollectionZhifubao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.transfer_record_collection_zhifubao
     *
     * @param transferRecordCollectionZhifubao the value for transfer_record.transfer_record_collection_zhifubao
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setTransferRecordCollectionZhifubao(String transferRecordCollectionZhifubao) {
        this.transferRecordCollectionZhifubao = transferRecordCollectionZhifubao == null ? null : transferRecordCollectionZhifubao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.transfer_record_collection_zhifubao_id
     *
     * @return the value of transfer_record.transfer_record_collection_zhifubao_id
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public String getTransferRecordCollectionZhifubaoId() {
        return transferRecordCollectionZhifubaoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.transfer_record_collection_zhifubao_id
     *
     * @param transferRecordCollectionZhifubaoId the value for transfer_record.transfer_record_collection_zhifubao_id
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setTransferRecordCollectionZhifubaoId(String transferRecordCollectionZhifubaoId) {
        this.transferRecordCollectionZhifubaoId = transferRecordCollectionZhifubaoId == null ? null : transferRecordCollectionZhifubaoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.transfer_record_collection_name
     *
     * @return the value of transfer_record.transfer_record_collection_name
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public String getTransferRecordCollectionName() {
        return transferRecordCollectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.transfer_record_collection_name
     *
     * @param transferRecordCollectionName the value for transfer_record.transfer_record_collection_name
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setTransferRecordCollectionName(String transferRecordCollectionName) {
        this.transferRecordCollectionName = transferRecordCollectionName == null ? null : transferRecordCollectionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.transfer_record_remark
     *
     * @return the value of transfer_record.transfer_record_remark
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public String getTransferRecordRemark() {
        return transferRecordRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.transfer_record_remark
     *
     * @param transferRecordRemark the value for transfer_record.transfer_record_remark
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setTransferRecordRemark(String transferRecordRemark) {
        this.transferRecordRemark = transferRecordRemark == null ? null : transferRecordRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.transfer_record_flow
     *
     * @return the value of transfer_record.transfer_record_flow
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public String getTransferRecordFlow() {
        return transferRecordFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.transfer_record_flow
     *
     * @param transferRecordFlow the value for transfer_record.transfer_record_flow
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setTransferRecordFlow(String transferRecordFlow) {
        this.transferRecordFlow = transferRecordFlow == null ? null : transferRecordFlow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.transfer_record_status
     *
     * @return the value of transfer_record.transfer_record_status
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public String getTransferRecordStatus() {
        return transferRecordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.transfer_record_status
     *
     * @param transferRecordStatus the value for transfer_record.transfer_record_status
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setTransferRecordStatus(String transferRecordStatus) {
        this.transferRecordStatus = transferRecordStatus == null ? null : transferRecordStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.transfer_record_product_name
     *
     * @return the value of transfer_record.transfer_record_product_name
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public String getTransferRecordProductName() {
        return transferRecordProductName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.transfer_record_product_name
     *
     * @param transferRecordProductName the value for transfer_record.transfer_record_product_name
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setTransferRecordProductName(String transferRecordProductName) {
        this.transferRecordProductName = transferRecordProductName == null ? null : transferRecordProductName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.transfer_record_index
     *
     * @return the value of transfer_record.transfer_record_index
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public String getTransferRecordIndex() {
        return transferRecordIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.transfer_record_index
     *
     * @param transferRecordIndex the value for transfer_record.transfer_record_index
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setTransferRecordIndex(String transferRecordIndex) {
        this.transferRecordIndex = transferRecordIndex == null ? null : transferRecordIndex.trim();
    }
}