package com.judge.demo.Entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TransferRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transfer_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transfer_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transfer_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transfer_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transfer_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public TransferRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table transfer_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTransferRecordIdIsNull() {
            addCriterion("transfer_record_id is null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordIdIsNotNull() {
            addCriterion("transfer_record_id is not null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordIdEqualTo(Long value) {
            addCriterion("transfer_record_id =", value, "transferRecordId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordIdNotEqualTo(Long value) {
            addCriterion("transfer_record_id <>", value, "transferRecordId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordIdGreaterThan(Long value) {
            addCriterion("transfer_record_id >", value, "transferRecordId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordIdGreaterThanOrEqualTo(Long value) {
            addCriterion("transfer_record_id >=", value, "transferRecordId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordIdLessThan(Long value) {
            addCriterion("transfer_record_id <", value, "transferRecordId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordIdLessThanOrEqualTo(Long value) {
            addCriterion("transfer_record_id <=", value, "transferRecordId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordIdIn(List<Long> values) {
            addCriterion("transfer_record_id in", values, "transferRecordId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordIdNotIn(List<Long> values) {
            addCriterion("transfer_record_id not in", values, "transferRecordId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordIdBetween(Long value1, Long value2) {
            addCriterion("transfer_record_id between", value1, value2, "transferRecordId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordIdNotBetween(Long value1, Long value2) {
            addCriterion("transfer_record_id not between", value1, value2, "transferRecordId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowIdIsNull() {
            addCriterion("transfer_record_flow_id is null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowIdIsNotNull() {
            addCriterion("transfer_record_flow_id is not null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowIdEqualTo(String value) {
            addCriterion("transfer_record_flow_id =", value, "transferRecordFlowId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowIdNotEqualTo(String value) {
            addCriterion("transfer_record_flow_id <>", value, "transferRecordFlowId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowIdGreaterThan(String value) {
            addCriterion("transfer_record_flow_id >", value, "transferRecordFlowId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowIdGreaterThanOrEqualTo(String value) {
            addCriterion("transfer_record_flow_id >=", value, "transferRecordFlowId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowIdLessThan(String value) {
            addCriterion("transfer_record_flow_id <", value, "transferRecordFlowId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowIdLessThanOrEqualTo(String value) {
            addCriterion("transfer_record_flow_id <=", value, "transferRecordFlowId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowIdLike(String value) {
            addCriterion("transfer_record_flow_id like", value, "transferRecordFlowId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowIdNotLike(String value) {
            addCriterion("transfer_record_flow_id not like", value, "transferRecordFlowId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowIdIn(List<String> values) {
            addCriterion("transfer_record_flow_id in", values, "transferRecordFlowId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowIdNotIn(List<String> values) {
            addCriterion("transfer_record_flow_id not in", values, "transferRecordFlowId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowIdBetween(String value1, String value2) {
            addCriterion("transfer_record_flow_id between", value1, value2, "transferRecordFlowId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowIdNotBetween(String value1, String value2) {
            addCriterion("transfer_record_flow_id not between", value1, value2, "transferRecordFlowId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCreateTimeIsNull() {
            addCriterion("transfer_record_create_time is null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCreateTimeIsNotNull() {
            addCriterion("transfer_record_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCreateTimeEqualTo(Date value) {
            addCriterion("transfer_record_create_time =", value, "transferRecordCreateTime");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCreateTimeNotEqualTo(Date value) {
            addCriterion("transfer_record_create_time <>", value, "transferRecordCreateTime");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCreateTimeGreaterThan(Date value) {
            addCriterion("transfer_record_create_time >", value, "transferRecordCreateTime");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("transfer_record_create_time >=", value, "transferRecordCreateTime");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCreateTimeLessThan(Date value) {
            addCriterion("transfer_record_create_time <", value, "transferRecordCreateTime");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("transfer_record_create_time <=", value, "transferRecordCreateTime");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCreateTimeIn(List<Date> values) {
            addCriterion("transfer_record_create_time in", values, "transferRecordCreateTime");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCreateTimeNotIn(List<Date> values) {
            addCriterion("transfer_record_create_time not in", values, "transferRecordCreateTime");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCreateTimeBetween(Date value1, Date value2) {
            addCriterion("transfer_record_create_time between", value1, value2, "transferRecordCreateTime");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("transfer_record_create_time not between", value1, value2, "transferRecordCreateTime");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayTimeIsNull() {
            addCriterion("transfer_record_pay_time is null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayTimeIsNotNull() {
            addCriterion("transfer_record_pay_time is not null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayTimeEqualTo(Date value) {
            addCriterion("transfer_record_pay_time =", value, "transferRecordPayTime");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayTimeNotEqualTo(Date value) {
            addCriterion("transfer_record_pay_time <>", value, "transferRecordPayTime");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayTimeGreaterThan(Date value) {
            addCriterion("transfer_record_pay_time >", value, "transferRecordPayTime");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("transfer_record_pay_time >=", value, "transferRecordPayTime");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayTimeLessThan(Date value) {
            addCriterion("transfer_record_pay_time <", value, "transferRecordPayTime");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayTimeLessThanOrEqualTo(Date value) {
            addCriterion("transfer_record_pay_time <=", value, "transferRecordPayTime");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayTimeIn(List<Date> values) {
            addCriterion("transfer_record_pay_time in", values, "transferRecordPayTime");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayTimeNotIn(List<Date> values) {
            addCriterion("transfer_record_pay_time not in", values, "transferRecordPayTime");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayTimeBetween(Date value1, Date value2) {
            addCriterion("transfer_record_pay_time between", value1, value2, "transferRecordPayTime");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayTimeNotBetween(Date value1, Date value2) {
            addCriterion("transfer_record_pay_time not between", value1, value2, "transferRecordPayTime");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayFeeIsNull() {
            addCriterion("transfer_record_pay_fee is null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayFeeIsNotNull() {
            addCriterion("transfer_record_pay_fee is not null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayFeeEqualTo(Double value) {
            addCriterion("transfer_record_pay_fee =", value, "transferRecordPayFee");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayFeeNotEqualTo(Double value) {
            addCriterion("transfer_record_pay_fee <>", value, "transferRecordPayFee");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayFeeGreaterThan(Double value) {
            addCriterion("transfer_record_pay_fee >", value, "transferRecordPayFee");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayFeeGreaterThanOrEqualTo(Double value) {
            addCriterion("transfer_record_pay_fee >=", value, "transferRecordPayFee");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayFeeLessThan(Double value) {
            addCriterion("transfer_record_pay_fee <", value, "transferRecordPayFee");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayFeeLessThanOrEqualTo(Double value) {
            addCriterion("transfer_record_pay_fee <=", value, "transferRecordPayFee");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayFeeIn(List<Double> values) {
            addCriterion("transfer_record_pay_fee in", values, "transferRecordPayFee");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayFeeNotIn(List<Double> values) {
            addCriterion("transfer_record_pay_fee not in", values, "transferRecordPayFee");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayFeeBetween(Double value1, Double value2) {
            addCriterion("transfer_record_pay_fee between", value1, value2, "transferRecordPayFee");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayFeeNotBetween(Double value1, Double value2) {
            addCriterion("transfer_record_pay_fee not between", value1, value2, "transferRecordPayFee");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoIsNull() {
            addCriterion("transfer_record_pay_zhifubao is null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoIsNotNull() {
            addCriterion("transfer_record_pay_zhifubao is not null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoEqualTo(String value) {
            addCriterion("transfer_record_pay_zhifubao =", value, "transferRecordPayZhifubao");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoNotEqualTo(String value) {
            addCriterion("transfer_record_pay_zhifubao <>", value, "transferRecordPayZhifubao");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoGreaterThan(String value) {
            addCriterion("transfer_record_pay_zhifubao >", value, "transferRecordPayZhifubao");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoGreaterThanOrEqualTo(String value) {
            addCriterion("transfer_record_pay_zhifubao >=", value, "transferRecordPayZhifubao");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoLessThan(String value) {
            addCriterion("transfer_record_pay_zhifubao <", value, "transferRecordPayZhifubao");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoLessThanOrEqualTo(String value) {
            addCriterion("transfer_record_pay_zhifubao <=", value, "transferRecordPayZhifubao");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoLike(String value) {
            addCriterion("transfer_record_pay_zhifubao like", value, "transferRecordPayZhifubao");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoNotLike(String value) {
            addCriterion("transfer_record_pay_zhifubao not like", value, "transferRecordPayZhifubao");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoIn(List<String> values) {
            addCriterion("transfer_record_pay_zhifubao in", values, "transferRecordPayZhifubao");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoNotIn(List<String> values) {
            addCriterion("transfer_record_pay_zhifubao not in", values, "transferRecordPayZhifubao");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoBetween(String value1, String value2) {
            addCriterion("transfer_record_pay_zhifubao between", value1, value2, "transferRecordPayZhifubao");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoNotBetween(String value1, String value2) {
            addCriterion("transfer_record_pay_zhifubao not between", value1, value2, "transferRecordPayZhifubao");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoIdIsNull() {
            addCriterion("transfer_record_pay_zhifubao_id is null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoIdIsNotNull() {
            addCriterion("transfer_record_pay_zhifubao_id is not null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoIdEqualTo(String value) {
            addCriterion("transfer_record_pay_zhifubao_id =", value, "transferRecordPayZhifubaoId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoIdNotEqualTo(String value) {
            addCriterion("transfer_record_pay_zhifubao_id <>", value, "transferRecordPayZhifubaoId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoIdGreaterThan(String value) {
            addCriterion("transfer_record_pay_zhifubao_id >", value, "transferRecordPayZhifubaoId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoIdGreaterThanOrEqualTo(String value) {
            addCriterion("transfer_record_pay_zhifubao_id >=", value, "transferRecordPayZhifubaoId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoIdLessThan(String value) {
            addCriterion("transfer_record_pay_zhifubao_id <", value, "transferRecordPayZhifubaoId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoIdLessThanOrEqualTo(String value) {
            addCriterion("transfer_record_pay_zhifubao_id <=", value, "transferRecordPayZhifubaoId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoIdLike(String value) {
            addCriterion("transfer_record_pay_zhifubao_id like", value, "transferRecordPayZhifubaoId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoIdNotLike(String value) {
            addCriterion("transfer_record_pay_zhifubao_id not like", value, "transferRecordPayZhifubaoId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoIdIn(List<String> values) {
            addCriterion("transfer_record_pay_zhifubao_id in", values, "transferRecordPayZhifubaoId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoIdNotIn(List<String> values) {
            addCriterion("transfer_record_pay_zhifubao_id not in", values, "transferRecordPayZhifubaoId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoIdBetween(String value1, String value2) {
            addCriterion("transfer_record_pay_zhifubao_id between", value1, value2, "transferRecordPayZhifubaoId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayZhifubaoIdNotBetween(String value1, String value2) {
            addCriterion("transfer_record_pay_zhifubao_id not between", value1, value2, "transferRecordPayZhifubaoId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayNameIsNull() {
            addCriterion("transfer_record_pay_name is null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayNameIsNotNull() {
            addCriterion("transfer_record_pay_name is not null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayNameEqualTo(String value) {
            addCriterion("transfer_record_pay_name =", value, "transferRecordPayName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayNameNotEqualTo(String value) {
            addCriterion("transfer_record_pay_name <>", value, "transferRecordPayName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayNameGreaterThan(String value) {
            addCriterion("transfer_record_pay_name >", value, "transferRecordPayName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayNameGreaterThanOrEqualTo(String value) {
            addCriterion("transfer_record_pay_name >=", value, "transferRecordPayName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayNameLessThan(String value) {
            addCriterion("transfer_record_pay_name <", value, "transferRecordPayName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayNameLessThanOrEqualTo(String value) {
            addCriterion("transfer_record_pay_name <=", value, "transferRecordPayName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayNameLike(String value) {
            addCriterion("transfer_record_pay_name like", value, "transferRecordPayName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayNameNotLike(String value) {
            addCriterion("transfer_record_pay_name not like", value, "transferRecordPayName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayNameIn(List<String> values) {
            addCriterion("transfer_record_pay_name in", values, "transferRecordPayName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayNameNotIn(List<String> values) {
            addCriterion("transfer_record_pay_name not in", values, "transferRecordPayName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayNameBetween(String value1, String value2) {
            addCriterion("transfer_record_pay_name between", value1, value2, "transferRecordPayName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordPayNameNotBetween(String value1, String value2) {
            addCriterion("transfer_record_pay_name not between", value1, value2, "transferRecordPayName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoIsNull() {
            addCriterion("transfer_record_collection_zhifubao is null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoIsNotNull() {
            addCriterion("transfer_record_collection_zhifubao is not null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoEqualTo(String value) {
            addCriterion("transfer_record_collection_zhifubao =", value, "transferRecordCollectionZhifubao");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoNotEqualTo(String value) {
            addCriterion("transfer_record_collection_zhifubao <>", value, "transferRecordCollectionZhifubao");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoGreaterThan(String value) {
            addCriterion("transfer_record_collection_zhifubao >", value, "transferRecordCollectionZhifubao");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoGreaterThanOrEqualTo(String value) {
            addCriterion("transfer_record_collection_zhifubao >=", value, "transferRecordCollectionZhifubao");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoLessThan(String value) {
            addCriterion("transfer_record_collection_zhifubao <", value, "transferRecordCollectionZhifubao");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoLessThanOrEqualTo(String value) {
            addCriterion("transfer_record_collection_zhifubao <=", value, "transferRecordCollectionZhifubao");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoLike(String value) {
            addCriterion("transfer_record_collection_zhifubao like", value, "transferRecordCollectionZhifubao");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoNotLike(String value) {
            addCriterion("transfer_record_collection_zhifubao not like", value, "transferRecordCollectionZhifubao");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoIn(List<String> values) {
            addCriterion("transfer_record_collection_zhifubao in", values, "transferRecordCollectionZhifubao");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoNotIn(List<String> values) {
            addCriterion("transfer_record_collection_zhifubao not in", values, "transferRecordCollectionZhifubao");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoBetween(String value1, String value2) {
            addCriterion("transfer_record_collection_zhifubao between", value1, value2, "transferRecordCollectionZhifubao");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoNotBetween(String value1, String value2) {
            addCriterion("transfer_record_collection_zhifubao not between", value1, value2, "transferRecordCollectionZhifubao");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoIdIsNull() {
            addCriterion("transfer_record_collection_zhifubao_id is null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoIdIsNotNull() {
            addCriterion("transfer_record_collection_zhifubao_id is not null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoIdEqualTo(String value) {
            addCriterion("transfer_record_collection_zhifubao_id =", value, "transferRecordCollectionZhifubaoId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoIdNotEqualTo(String value) {
            addCriterion("transfer_record_collection_zhifubao_id <>", value, "transferRecordCollectionZhifubaoId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoIdGreaterThan(String value) {
            addCriterion("transfer_record_collection_zhifubao_id >", value, "transferRecordCollectionZhifubaoId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoIdGreaterThanOrEqualTo(String value) {
            addCriterion("transfer_record_collection_zhifubao_id >=", value, "transferRecordCollectionZhifubaoId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoIdLessThan(String value) {
            addCriterion("transfer_record_collection_zhifubao_id <", value, "transferRecordCollectionZhifubaoId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoIdLessThanOrEqualTo(String value) {
            addCriterion("transfer_record_collection_zhifubao_id <=", value, "transferRecordCollectionZhifubaoId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoIdLike(String value) {
            addCriterion("transfer_record_collection_zhifubao_id like", value, "transferRecordCollectionZhifubaoId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoIdNotLike(String value) {
            addCriterion("transfer_record_collection_zhifubao_id not like", value, "transferRecordCollectionZhifubaoId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoIdIn(List<String> values) {
            addCriterion("transfer_record_collection_zhifubao_id in", values, "transferRecordCollectionZhifubaoId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoIdNotIn(List<String> values) {
            addCriterion("transfer_record_collection_zhifubao_id not in", values, "transferRecordCollectionZhifubaoId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoIdBetween(String value1, String value2) {
            addCriterion("transfer_record_collection_zhifubao_id between", value1, value2, "transferRecordCollectionZhifubaoId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionZhifubaoIdNotBetween(String value1, String value2) {
            addCriterion("transfer_record_collection_zhifubao_id not between", value1, value2, "transferRecordCollectionZhifubaoId");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionNameIsNull() {
            addCriterion("transfer_record_collection_name is null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionNameIsNotNull() {
            addCriterion("transfer_record_collection_name is not null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionNameEqualTo(String value) {
            addCriterion("transfer_record_collection_name =", value, "transferRecordCollectionName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionNameNotEqualTo(String value) {
            addCriterion("transfer_record_collection_name <>", value, "transferRecordCollectionName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionNameGreaterThan(String value) {
            addCriterion("transfer_record_collection_name >", value, "transferRecordCollectionName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionNameGreaterThanOrEqualTo(String value) {
            addCriterion("transfer_record_collection_name >=", value, "transferRecordCollectionName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionNameLessThan(String value) {
            addCriterion("transfer_record_collection_name <", value, "transferRecordCollectionName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionNameLessThanOrEqualTo(String value) {
            addCriterion("transfer_record_collection_name <=", value, "transferRecordCollectionName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionNameLike(String value) {
            addCriterion("transfer_record_collection_name like", value, "transferRecordCollectionName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionNameNotLike(String value) {
            addCriterion("transfer_record_collection_name not like", value, "transferRecordCollectionName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionNameIn(List<String> values) {
            addCriterion("transfer_record_collection_name in", values, "transferRecordCollectionName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionNameNotIn(List<String> values) {
            addCriterion("transfer_record_collection_name not in", values, "transferRecordCollectionName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionNameBetween(String value1, String value2) {
            addCriterion("transfer_record_collection_name between", value1, value2, "transferRecordCollectionName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordCollectionNameNotBetween(String value1, String value2) {
            addCriterion("transfer_record_collection_name not between", value1, value2, "transferRecordCollectionName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordRemarkIsNull() {
            addCriterion("transfer_record_remark is null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordRemarkIsNotNull() {
            addCriterion("transfer_record_remark is not null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordRemarkEqualTo(String value) {
            addCriterion("transfer_record_remark =", value, "transferRecordRemark");
            return (Criteria) this;
        }

        public Criteria andTransferRecordRemarkNotEqualTo(String value) {
            addCriterion("transfer_record_remark <>", value, "transferRecordRemark");
            return (Criteria) this;
        }

        public Criteria andTransferRecordRemarkGreaterThan(String value) {
            addCriterion("transfer_record_remark >", value, "transferRecordRemark");
            return (Criteria) this;
        }

        public Criteria andTransferRecordRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("transfer_record_remark >=", value, "transferRecordRemark");
            return (Criteria) this;
        }

        public Criteria andTransferRecordRemarkLessThan(String value) {
            addCriterion("transfer_record_remark <", value, "transferRecordRemark");
            return (Criteria) this;
        }

        public Criteria andTransferRecordRemarkLessThanOrEqualTo(String value) {
            addCriterion("transfer_record_remark <=", value, "transferRecordRemark");
            return (Criteria) this;
        }

        public Criteria andTransferRecordRemarkLike(String value) {
            addCriterion("transfer_record_remark like", value, "transferRecordRemark");
            return (Criteria) this;
        }

        public Criteria andTransferRecordRemarkNotLike(String value) {
            addCriterion("transfer_record_remark not like", value, "transferRecordRemark");
            return (Criteria) this;
        }

        public Criteria andTransferRecordRemarkIn(List<String> values) {
            addCriterion("transfer_record_remark in", values, "transferRecordRemark");
            return (Criteria) this;
        }

        public Criteria andTransferRecordRemarkNotIn(List<String> values) {
            addCriterion("transfer_record_remark not in", values, "transferRecordRemark");
            return (Criteria) this;
        }

        public Criteria andTransferRecordRemarkBetween(String value1, String value2) {
            addCriterion("transfer_record_remark between", value1, value2, "transferRecordRemark");
            return (Criteria) this;
        }

        public Criteria andTransferRecordRemarkNotBetween(String value1, String value2) {
            addCriterion("transfer_record_remark not between", value1, value2, "transferRecordRemark");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowIsNull() {
            addCriterion("transfer_record_flow is null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowIsNotNull() {
            addCriterion("transfer_record_flow is not null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowEqualTo(String value) {
            addCriterion("transfer_record_flow =", value, "transferRecordFlow");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowNotEqualTo(String value) {
            addCriterion("transfer_record_flow <>", value, "transferRecordFlow");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowGreaterThan(String value) {
            addCriterion("transfer_record_flow >", value, "transferRecordFlow");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowGreaterThanOrEqualTo(String value) {
            addCriterion("transfer_record_flow >=", value, "transferRecordFlow");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowLessThan(String value) {
            addCriterion("transfer_record_flow <", value, "transferRecordFlow");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowLessThanOrEqualTo(String value) {
            addCriterion("transfer_record_flow <=", value, "transferRecordFlow");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowLike(String value) {
            addCriterion("transfer_record_flow like", value, "transferRecordFlow");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowNotLike(String value) {
            addCriterion("transfer_record_flow not like", value, "transferRecordFlow");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowIn(List<String> values) {
            addCriterion("transfer_record_flow in", values, "transferRecordFlow");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowNotIn(List<String> values) {
            addCriterion("transfer_record_flow not in", values, "transferRecordFlow");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowBetween(String value1, String value2) {
            addCriterion("transfer_record_flow between", value1, value2, "transferRecordFlow");
            return (Criteria) this;
        }

        public Criteria andTransferRecordFlowNotBetween(String value1, String value2) {
            addCriterion("transfer_record_flow not between", value1, value2, "transferRecordFlow");
            return (Criteria) this;
        }

        public Criteria andTransferRecordStatusIsNull() {
            addCriterion("transfer_record_status is null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordStatusIsNotNull() {
            addCriterion("transfer_record_status is not null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordStatusEqualTo(String value) {
            addCriterion("transfer_record_status =", value, "transferRecordStatus");
            return (Criteria) this;
        }

        public Criteria andTransferRecordStatusNotEqualTo(String value) {
            addCriterion("transfer_record_status <>", value, "transferRecordStatus");
            return (Criteria) this;
        }

        public Criteria andTransferRecordStatusGreaterThan(String value) {
            addCriterion("transfer_record_status >", value, "transferRecordStatus");
            return (Criteria) this;
        }

        public Criteria andTransferRecordStatusGreaterThanOrEqualTo(String value) {
            addCriterion("transfer_record_status >=", value, "transferRecordStatus");
            return (Criteria) this;
        }

        public Criteria andTransferRecordStatusLessThan(String value) {
            addCriterion("transfer_record_status <", value, "transferRecordStatus");
            return (Criteria) this;
        }

        public Criteria andTransferRecordStatusLessThanOrEqualTo(String value) {
            addCriterion("transfer_record_status <=", value, "transferRecordStatus");
            return (Criteria) this;
        }

        public Criteria andTransferRecordStatusLike(String value) {
            addCriterion("transfer_record_status like", value, "transferRecordStatus");
            return (Criteria) this;
        }

        public Criteria andTransferRecordStatusNotLike(String value) {
            addCriterion("transfer_record_status not like", value, "transferRecordStatus");
            return (Criteria) this;
        }

        public Criteria andTransferRecordStatusIn(List<String> values) {
            addCriterion("transfer_record_status in", values, "transferRecordStatus");
            return (Criteria) this;
        }

        public Criteria andTransferRecordStatusNotIn(List<String> values) {
            addCriterion("transfer_record_status not in", values, "transferRecordStatus");
            return (Criteria) this;
        }

        public Criteria andTransferRecordStatusBetween(String value1, String value2) {
            addCriterion("transfer_record_status between", value1, value2, "transferRecordStatus");
            return (Criteria) this;
        }

        public Criteria andTransferRecordStatusNotBetween(String value1, String value2) {
            addCriterion("transfer_record_status not between", value1, value2, "transferRecordStatus");
            return (Criteria) this;
        }

        public Criteria andTransferRecordProductNameIsNull() {
            addCriterion("transfer_record_product_name is null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordProductNameIsNotNull() {
            addCriterion("transfer_record_product_name is not null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordProductNameEqualTo(String value) {
            addCriterion("transfer_record_product_name =", value, "transferRecordProductName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordProductNameNotEqualTo(String value) {
            addCriterion("transfer_record_product_name <>", value, "transferRecordProductName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordProductNameGreaterThan(String value) {
            addCriterion("transfer_record_product_name >", value, "transferRecordProductName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("transfer_record_product_name >=", value, "transferRecordProductName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordProductNameLessThan(String value) {
            addCriterion("transfer_record_product_name <", value, "transferRecordProductName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordProductNameLessThanOrEqualTo(String value) {
            addCriterion("transfer_record_product_name <=", value, "transferRecordProductName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordProductNameLike(String value) {
            addCriterion("transfer_record_product_name like", value, "transferRecordProductName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordProductNameNotLike(String value) {
            addCriterion("transfer_record_product_name not like", value, "transferRecordProductName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordProductNameIn(List<String> values) {
            addCriterion("transfer_record_product_name in", values, "transferRecordProductName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordProductNameNotIn(List<String> values) {
            addCriterion("transfer_record_product_name not in", values, "transferRecordProductName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordProductNameBetween(String value1, String value2) {
            addCriterion("transfer_record_product_name between", value1, value2, "transferRecordProductName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordProductNameNotBetween(String value1, String value2) {
            addCriterion("transfer_record_product_name not between", value1, value2, "transferRecordProductName");
            return (Criteria) this;
        }

        public Criteria andTransferRecordIndexIsNull() {
            addCriterion("transfer_record_index is null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordIndexIsNotNull() {
            addCriterion("transfer_record_index is not null");
            return (Criteria) this;
        }

        public Criteria andTransferRecordIndexEqualTo(String value) {
            addCriterion("transfer_record_index =", value, "transferRecordIndex");
            return (Criteria) this;
        }

        public Criteria andTransferRecordIndexNotEqualTo(String value) {
            addCriterion("transfer_record_index <>", value, "transferRecordIndex");
            return (Criteria) this;
        }

        public Criteria andTransferRecordIndexGreaterThan(String value) {
            addCriterion("transfer_record_index >", value, "transferRecordIndex");
            return (Criteria) this;
        }

        public Criteria andTransferRecordIndexGreaterThanOrEqualTo(String value) {
            addCriterion("transfer_record_index >=", value, "transferRecordIndex");
            return (Criteria) this;
        }

        public Criteria andTransferRecordIndexLessThan(String value) {
            addCriterion("transfer_record_index <", value, "transferRecordIndex");
            return (Criteria) this;
        }

        public Criteria andTransferRecordIndexLessThanOrEqualTo(String value) {
            addCriterion("transfer_record_index <=", value, "transferRecordIndex");
            return (Criteria) this;
        }

        public Criteria andTransferRecordIndexLike(String value) {
            addCriterion("transfer_record_index like", value, "transferRecordIndex");
            return (Criteria) this;
        }

        public Criteria andTransferRecordIndexNotLike(String value) {
            addCriterion("transfer_record_index not like", value, "transferRecordIndex");
            return (Criteria) this;
        }

        public Criteria andTransferRecordIndexIn(List<String> values) {
            addCriterion("transfer_record_index in", values, "transferRecordIndex");
            return (Criteria) this;
        }

        public Criteria andTransferRecordIndexNotIn(List<String> values) {
            addCriterion("transfer_record_index not in", values, "transferRecordIndex");
            return (Criteria) this;
        }

        public Criteria andTransferRecordIndexBetween(String value1, String value2) {
            addCriterion("transfer_record_index between", value1, value2, "transferRecordIndex");
            return (Criteria) this;
        }

        public Criteria andTransferRecordIndexNotBetween(String value1, String value2) {
            addCriterion("transfer_record_index not between", value1, value2, "transferRecordIndex");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table transfer_record
     *
     * @mbggenerated do_not_delete_during_merge Wed Oct 24 01:45:54 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table transfer_record
     *
     * @mbggenerated Wed Oct 24 01:45:54 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}