package com.judge.demo.Dao;

import com.judge.demo.Entity.PersonRecord;
import com.judge.demo.Entity.PersonRecordExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface PersonRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    int countByExample(PersonRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    int deleteByExample(PersonRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    int deleteByPrimaryKey(Long pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    int insert(PersonRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    int insertSelective(PersonRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    List<PersonRecord> selectByExample(PersonRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    PersonRecord selectByPrimaryKey(Long pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") PersonRecord record, @Param("example") PersonRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    int updateByExample(@Param("record") PersonRecord record, @Param("example") PersonRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    int updateByPrimaryKeySelective(PersonRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_record
     *
     * @mbggenerated Fri Oct 26 17:48:36 CST 2018
     */
    int updateByPrimaryKey(PersonRecord record);
}